dynamic: install


all: install


install:
	cp -f libwlbcmcrypto.so_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/lib/libwlbcmcrypto.so
	cp -f libwlbcmshared.so_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/lib/libwlbcmshared.so
	cp -f libwlupnp.so_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/lib/libwlupnp.so
	cp -f eapd_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/bin/eapd
	cp -f lld2d_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/bin/lld2d
	cp -f wrt54g.large.ico_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/etc/wrt54g.large.ico
	cp -f wrt54g.small.ico_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/etc/wrt54g.small.ico
	cp -f nas_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/bin/nas
	cp -f nvram_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/bin/nvram
	cp -f libnvram.so_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/lib/libnvram.so
	cp -f nvram_params_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/etc/wlan/nvram_params
	cp -f nvramUpdate_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/bin/nvramUpdate
	cp -f wlctl_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/bin/wlctl
	cp -f libwlctl.so_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/lib/libwlctl.so
	cp -f wlmngr_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/bin/wlmngr
	cp -f wlevt_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/bin/wlevt
	cp -f libwlmngr.so_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/lib/libwlmngr.so
	cp -f libwlcsm.so_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/lib/libwlcsm.so
	cp -f wps_monitor_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/bin/wps_monitor
	cp -f libwps.so_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/lib/libwps.so
	cp -f epi_ttcp_DSL-2492GNAU-B3BC_save $(INSTALL_DIR)/bin/epi_ttcp
