echo ********************Generate SMT CFE END********************
cp ../../defaultcfg/132TUZ0_TE.rom ./132TUZ0_TE.rom
./CompressConfig_CFE ./132TUZ0_TE.rom ./132TUZ0_TE.rom_COMP
cat ./cfe63268nand128.bm ./132TUZ0_TE.rom_COMP > ./cfe63268nand128.tmp
./createboot --boardid=963168VX --numbermac=12 --macaddr=CC:5D:4E:00:00:01 --countrycode=F5 --manufactureConfig=1 --modelid=600a --tp=0 --psisize=128 --backuppsi= --inputfile=cfe63268nand128.tmp --outputfile=cfe63268nand128_Release_TE.bin --cfeSize=$(find . -name cfe63268nand128.bm -printf '%s')
./createboot --boardid=963168VX --numbermac=12 --macaddr=CC:5D:4E:00:00:01 --countrycode=F5 --manufactureConfig=1 --modelid=600a --tp=0 --psisize=128 --empty --backuppsi= --inputfile=cfe63268nand128.tmp --outputfile=cfe63268nand128_TE.bin --cfeSize=$(find . -name cfe63268nand128.bm -printf '%s')
echo ********************Generate SMT CFE END********************
echo ********************Generate SMT file BEGIN********************
./CompressConfig_RAS ./132VQI.rom ./132VQI.rom_COMP
./bcmZyNandImageBuilder --output bcmDSL-2492GNAU-B3BC_cfe_fs_kernel_NAND128_TE --chip 63268 --board 963168VX --internalversion="1.00(AAJX.8)" --externalversion="1.00(AAJX.8)" --modelid=600a --cmodelid=600a --cfefile cfe63268nand128_TE.bin --imgdefaultfile=132VQI.rom_COMP --romdsig 0 --romdfile= --rootfsfile rootfs128kb.img --include-cfe
./createZyNandimg --boardid=963168VX --numbermac=12 --macaddr=CC:5D:4E:00:00:01 --countrycode=F5 --tp=0 --psisize=128 --gponsn= --gponpw= --backuppsi= --inputfile=bcmDSL-2492GNAU-B3BC_cfe_fs_kernel_NAND128_TE --outputfile=bcmDSL-2492GNAU-B3BC_flash_image_963168VX_NAND128_TE
./NANDimg_gen -v "1.00(AAJX.8)" -q 1 -t large -M 1
./NANDimg_gen -f bcmDSL-2492GNAU-B3BC_flash_image_963168VX_NAND128_TE -v "1.00(AAJX.8)" -i 150728_2019 -S 0 -s jffs2 -c on -q 1 -p 128 -t large -o brcom -e 512 -G 50
cat common_header.img partition_header.img > product_header.img
cat product_header.img partition_image.img > bcmDSL-2492GNAU-B3BC_SMT_963168VX_NAND128
cat partition_image.img > bcmDSL-2492GNAU-B3BC_SMT_963168VX_NAND128_partition_image
echo ********************Generate SMT file END********************
echo ********************Compare SMT file Begin********************
if [ "$(diff ./bcmDSL-2492GNAU-B3BC_SMT_963168VX_NAND128 ../bcmDSL-2492GNAU-B3BC_SMT_963168VX_NAND128)" = "" ]; then
echo -e "\033[32mThe SMT file ./bcmDSL-2492GNAU-B3BC_SMT_963168VX_NAND128 generated by GenSMT.sh is same as ../bcmDSL-2492GNAU-B3BC_SMT_963168VX_NAND128\033[0m"
else
echo -e "\033[33mThe SMT file ./bcmDSL-2492GNAU-B3BC_SMT_963168VX_NAND128 generated by GenSMT.sh is different as ../bcmDSL-2492GNAU-B3BC_SMT_963168VX_NAND128\033[0m"
fi
echo ********************Compare SMT file END********************
