#ifndef __MDM_OBJECTID_H__
#define __MDM_OBJECTID_H__


/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


/*!\file mdm_objectid.h 
 * \brief Automatically generated header file mdm_objectid.h
 */


/*! \brief InternetGatewayDevice. */
#define MDMOID_IGD  1

/*! \brief InternetGatewayDevice.X_5067F0_AutoexecCmd.{i}. */
#define MDMOID_AUTOEXEC_CMD  2

/*! \brief InternetGatewayDevice.X_5067F0_DebugPortMirrorCfg. */
#define MDMOID_DEBUG_PORT_MIRROR_CFG  3

/*! \brief InternetGatewayDevice.DeviceInfo. */
#define MDMOID_IGD_DEVICE_INFO  4

/*! \brief InternetGatewayDevice.DeviceInfo.X_5067F0_DualImage. */
#define MDMOID_DUAL_IMG  5

/*! \brief InternetGatewayDevice.UploadDiagnostics. */
#define MDMOID_UPLOAD_DIAGNOSTICS  6

/*! \brief InternetGatewayDevice.UploadDiagnostics.X_5067F0_Result.{i}. */
#define MDMOID_UPLOAD_DIAG_RESULT  7

/*! \brief InternetGatewayDevice.DownloadDiagnostics. */
#define MDMOID_DOWNLOAD_DIAGNOSTICS  8

/*! \brief InternetGatewayDevice.DownloadDiagnostics.X_5067F0_Result.{i}. */
#define MDMOID_DOWNLOAD_DIAG_RESULT  9

/*! \brief InternetGatewayDevice.UDPEchoConfig. */
#define MDMOID_UDP_ECHO_CFG  10

/*! \brief InternetGatewayDevice.DeviceInfo.VendorConfigFile.{i}. */
#define MDMOID_VENDOR_CONFIG_FILE  11

/*! \brief InternetGatewayDevice.CaptivePortal. */
#define MDMOID_CAPTIVE_PORTAL  12

/*! \brief InternetGatewayDevice.X_5067F0_BpaApiFlowHandle.{i}. */
#define MDMOID_BPA_API_FLOW_HANDLE  13

/*! \brief InternetGatewayDevice.X_5067F0_SyslogCfg. */
#define MDMOID_SYSLOG_CFG  14

/*! \brief InternetGatewayDevice.X_5067F0_LoginCfg. */
#define MDMOID_LOGIN_CFG  15

/*! \brief InternetGatewayDevice.X_5067F0_LoginCfg.X_5067F0_Login_Group.{i}. */
#define MDMOID_LOGIN_GRP  16

/*! \brief InternetGatewayDevice.X_5067F0_LoginCfg.X_5067F0_Login_Group.{i}.Use_Login_Info.{i}. */
#define MDMOID_USER_LOGIN_INFO  17

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg. */
#define MDMOID_APP_CFG  18

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.HttpdCfg. */
#define MDMOID_HTTPD_CFG  19

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.HttpdsCfg. */
#define MDMOID_HTTPDS_CFG  20

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.Tr69cCfg. */
#define MDMOID_TR69C_CFG  21

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.Tr64cCfg. */
#define MDMOID_TR64C_CFG  22

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.SshdCfg. */
#define MDMOID_SSHD_CFG  23

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.TelnetdCfg. */
#define MDMOID_TELNETD_CFG  24

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.ConsoledCfg. */
#define MDMOID_CONSOLED_CFG  25

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.SmdCfg. */
#define MDMOID_SMD_CFG  26

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.SskCfg. */
#define MDMOID_SSK_CFG  27

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.SnmpdCfg. */
#define MDMOID_SNMPD_CFG  28

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.FtpdCfg. */
#define MDMOID_FTPD_CFG  29

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.TftpdCfg. */
#define MDMOID_TFTPD_CFG  30

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.PppdCfg. */
#define MDMOID_PPPD_CFG  31

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.IcmpCfg. */
#define MDMOID_ICMP_CFG  32

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.UpnpCfg. */
#define MDMOID_UPNP_CFG  33

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.DnsProxyCfg. */
#define MDMOID_DNS_PROXY_CFG  34

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.DectdCfg. */
#define MDMOID_DECTD_CFG  35

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.VectoringCfg. */
#define MDMOID_VECTORING_CFG  36

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.OmcidCfg. */
#define MDMOID_OMCID_CFG  37

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.LaserdCfg. */
#define MDMOID_LASERD_CFG  38

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.OmciPmdCfg. */
#define MDMOID_OMCI_PMD_CFG  39

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.OsgidCfg. */
#define MDMOID_OSGID_CFG  40

/*! \brief InternetGatewayDevice.X_5067F0_EthernetSwitch. */
#define MDMOID_ETHERNET_SWITCH  41

/*! \brief InternetGatewayDevice.X_5067F0_PwrMngtCfg. */
#define MDMOID_PWR_MNGT  42

/*! \brief InternetGatewayDevice.X_5067F0_StandbyCfg. */
#define MDMOID_STANDBY_CFG  43

/*! \brief InternetGatewayDevice.X_5067F0_DualBoot. */
#define MDMOID_DUAL_BOOT  44

/*! \brief InternetGatewayDevice.X_5067F0_VOIPFilter. */
#define MDMOID_VOIP_FILTER  45

/*! \brief InternetGatewayDevice.X_5067F0_VOIPFilter.Domain.{i}. */
#define MDMOID_VOIP_FILTER_DOMAIN  46

/*! \brief InternetGatewayDevice.DeviceConfig. */
#define MDMOID_DEVICE_CONFIG  47

/*! \brief InternetGatewayDevice.ManagementServer. */
#define MDMOID_MANAGEMENT_SERVER  48

/*! \brief InternetGatewayDevice.ManagementServer.ManageableDevice.{i}. */
#define MDMOID_MANAGEABLE_DEVICE  49

/*! \brief InternetGatewayDevice.Time. */
#define MDMOID_TIME_SERVER_CFG  50

/*! \brief InternetGatewayDevice.Layer2Bridging. */
#define MDMOID_L2_BRIDGING  51

/*! \brief InternetGatewayDevice.Layer2Bridging.Bridge.{i}. */
#define MDMOID_L2_BRIDGING_ENTRY  52

/*! \brief InternetGatewayDevice.Layer2Bridging.Filter.{i}. */
#define MDMOID_L2_BRIDGING_FILTER  53

/*! \brief InternetGatewayDevice.Layer2Bridging.AvailableInterface.{i}. */
#define MDMOID_L2_BRIDGING_INTF  54

/*! \brief InternetGatewayDevice.QueueManagement. */
#define MDMOID_Q_MGMT  55

/*! \brief InternetGatewayDevice.QueueManagement.Classification.{i}. */
#define MDMOID_Q_MGMT_CLASSIFICATION  56

/*! \brief InternetGatewayDevice.QueueManagement.Policer.{i}. */
#define MDMOID_Q_MGMT_POLICER  57

/*! \brief InternetGatewayDevice.QueueManagement.Queue.{i}. */
#define MDMOID_Q_MGMT_QUEUE  58

/*! \brief InternetGatewayDevice.X_5067F0_TraceRouteDiagObject. */
#define MDMOID_TRACE_ROUTE_DIAG  59

/*! \brief InternetGatewayDevice.X_5067F0_TraceRouteDiagObject.RouteHops.{i}. */
#define MDMOID_TRACE_ROUTE_HOPS  60

/*! \brief InternetGatewayDevice.X_5067F0_NslookupDiagObject. */
#define MDMOID_NSLOOKUP_DIAG  61

/*! \brief InternetGatewayDevice.IPPingDiagnostics. */
#define MDMOID_IP_PING_DIAG  62

/*! \brief InternetGatewayDevice.EponSoftwareImage.{i}. */
#define MDMOID_EPON_SOFTWARE_IMAGE  63

/*! \brief InternetGatewayDevice.LANDevice.{i}. */
#define MDMOID_LAN_DEV  64

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IgmpSnoopingConfig. */
#define MDMOID_IGMP_SNOOPING_CFG  65

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement. */
#define MDMOID_LAN_HOST_CFG  66

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}. */
#define MDMOID_LAN_IP_INTF  67

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_5067F0_IPv6LanIntfAddress. */
#define MDMOID_I_PV6_LAN_INTF_ADDR  68

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_5067F0_IPv6LanIntfAddress.DelegatedAddress.{i}. */
#define MDMOID_DELEGATED_ADDRESS  69

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_5067F0_FirewallException.{i}. */
#define MDMOID_LAN_IP_INTF_FIREWALL_EXCEPTION  70

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_5067F0_IpFilterCfg.{i}. */
#define MDMOID_IP_FILTER_CFG  71

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPStaticAddress.{i}. */
#define MDMOID_DHCP_STATIC_ADDR  72

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPOption.{i}. */
#define MDMOID_LAN_HOST_OPTION  73

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPConditionalServingPool.{i}. */
#define MDMOID_DHCP_CONDITIONAL_SERVING  74

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPConditionalServingPool.{i}.DHCPOption.{i}. */
#define MDMOID_DHCP_COND_SERV_OPTION  75

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IPv6LANHostConfigManagement. */
#define MDMOID_I_PV6_LAN_HOST_CFG  76

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IPv6LANHostConfigManagement.RadvdConfigManagement. */
#define MDMOID_RADVD_CONFIG_MGT  77

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IPv6LANHostConfigManagement.RadvdConfigManagement.X_5067F0_DNSSLInfo. */
#define MDMOID_DNSSL_INFO  78

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IPv6LANHostConfigManagement.RadvdConfigManagement.ULAPrefixInfo. */
#define MDMOID_ULA_PREFIX_INFO  79

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IPv6LANHostConfigManagement.RadvdConfigManagement.PrefixInformation.{i}. */
#define MDMOID_PREFIX_INFO  80

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IPv6LANHostConfigManagement.X_5067F0_MldSnoopingConfig. */
#define MDMOID_MLD_SNOOPING_CFG  81

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IPv6LANHostConfigManagement.RejectPDValue.{i}. */
#define MDMOID_PD_CFG  82

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}. */
#define MDMOID_LAN_ETH_INTF  83

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_ETH_INTF_STATS  84

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}. */
#define MDMOID_LAN_USB_INTF  85

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_USB_INTF_STATS  86

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}. */
#define MDMOID_LAN_WLAN  87

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.AssociatedDevice.{i}. */
#define MDMOID_LAN_WLAN_ASSOCIATED_DEVICE_ENTRY  88

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WEPKey.{i}. */
#define MDMOID_LAN_WLAN_WEP_KEY  89

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.PreSharedKey.{i}. */
#define MDMOID_LAN_WLAN_PRE_SHARED_KEY  90

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.Stats. */
#define MDMOID_LAN_WLAN_STATS  91

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.APWMMParameter.{i}. */
#define MDMOID_APWMM_PARAMETER  92

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.STAWMMParameter.{i}. */
#define MDMOID_STAWMM_PARAMETER  93

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter. */
#define MDMOID_WLAN_ADAPTER  94

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlBaseCfg. */
#define MDMOID_WL_BASE_CFG  95

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlStaticWdsCfg.{i}. */
#define MDMOID_WL_STATIC_WDS_CFG  96

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlWdsCfg.{i}. */
#define MDMOID_WL_WDS_CFG  97

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlScanWdsCfg.{i}. */
#define MDMOID_WL_SCAN_WDS_CFG  98

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlMimoCfg. */
#define MDMOID_WL_MIMO_CFG  99

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlWmmCfg. */
#define MDMOID_WL_WMM_CFG  100

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlWmmCfg.WlAPWmmParameterCfg.{i}. */
#define MDMOID_AP_WMM_PARAMETER_CFG  101

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlWmmCfg.WlSTAWmmParameterCfg.{i}. */
#define MDMOID_STA_WMM_PARAMETER_CFG  102

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlSesCfg. */
#define MDMOID_WL_SES_CFG  103

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlVirtIntfCfg.{i}. */
#define MDMOID_WL_VIRT_INTF_CFG  104

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlVirtIntfCfg.{i}.WlMacFltCfg.{i}. */
#define MDMOID_WL_MAC_FLT  105

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlVirtIntfCfg.{i}.WlKey64Cfg.{i}. */
#define MDMOID_WL_KEY64_CFG  106

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlVirtIntfCfg.{i}.WlKey128Cfg.{i}. */
#define MDMOID_WL_KEY128_CFG  107

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlVirtIntfCfg.{i}.WlWpsCfg. */
#define MDMOID_WL_WPS_CFG  108

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.ScanTimeSet. */
#define MDMOID_SCAN_TIME_SET  109

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WLANVirtMbssConfiguration.{i}. */
#define MDMOID_LAN_WLAN_VIRT_MBSS  110

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WPS. */
#define MDMOID_LAN_WLAN_WPS  111

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WPS.Registrar.{i}. */
#define MDMOID_LAN_WLAN_WPS_REGISTRAR  112

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_LANMocaInterfaceConfig.{i}. */
#define MDMOID_LAN_MOCA_INTF  113

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_LANMocaInterfaceConfig.{i}.Status. */
#define MDMOID_LAN_MOCA_INTF_STATUS  114

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_LANMocaInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_MOCA_INTF_STATS  115

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_LANEponInterfaceConfig.{i}. */
#define MDMOID_LAN_EPON_INTF  116

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_LANEponInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_EPON_INTF_STATS  117

/*! \brief InternetGatewayDevice.LANDevice.{i}.Hosts. */
#define MDMOID_LAN_HOSTS  118

/*! \brief InternetGatewayDevice.LANDevice.{i}.Hosts.Host.{i}. */
#define MDMOID_LAN_HOST_ENTRY  119

/*! \brief InternetGatewayDevice.LANDevice.{i}.Hosts.Host6.{i}. */
#define MDMOID_I_PV6_LAN_HOST_ENTRY  120

/*! \brief InternetGatewayDevice.X_5067F0_HostsIconState.{i}. */
#define MDMOID_LAN_HOST_ICON_STATE  121

/*! \brief InternetGatewayDevice.WANDevice.{i}. */
#define MDMOID_WAN_DEV  122

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANCommonInterfaceConfig. */
#define MDMOID_WAN_COMMON_INTF_CFG  123

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_XTM_Interface_Stats.{i}. */
#define MDMOID_XTM_INTERFACE_STATS  124

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig. */
#define MDMOID_WAN_DSL_INTF_CFG  125

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.X_5067F0_BertTest. */
#define MDMOID_WAN_BERT_TEST  126

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats. */
#define MDMOID_WAN_DSL_INTF_STATS  127

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Total. */
#define MDMOID_WAN_DSL_INTF_STATS_TOTAL  128

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Showtime. */
#define MDMOID_WAN_DSL_INTF_STATS_SHOWTIME  129

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.CurrentDay. */
#define MDMOID_WAN_DSL_INTF_STATS_CURRENT_DAY  130

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.QuarterHour. */
#define MDMOID_WAN_DSL_INTF_STATS_QUARTER_HOUR  131

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.TestParams. */
#define MDMOID_WAN_DSL_TEST_PARAMS  132

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig. */
#define MDMOID_WAN_ETH_INTF  133

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig.X_5067F0_IPv6Address.{i}. */
#define MDMOID_I_PV6_ADDR  134

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig.Stats. */
#define MDMOID_WAN_ETH_INTF_STATS  135

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANMocaInterfaceConfig. */
#define MDMOID_WAN_MOCA_INTF  136

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANMocaInterfaceConfig.Status. */
#define MDMOID_WAN_MOCA_INTF_STATUS  137

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANMocaInterfaceConfig.Stats. */
#define MDMOID_WAN_MOCA_INTF_STATS  138

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_EponInterfaceConfig. */
#define MDMOID_WAN_EPON_INTF  139

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_EponInterfaceConfig.Stats. */
#define MDMOID_WAN_EPON_INTF_STATS  140

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_L2tpAcIntfConfig. */
#define MDMOID_L2TP_AC_INTF_CONFIG  141

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANPonInterfaceConfig. */
#define MDMOID_WAN_PON_INTF  142

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANPonInterfaceConfig.Stats. */
#define MDMOID_WAN_PON_INTF_STATUS  143

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLDiagnostics. */
#define MDMOID_WAN_DSL_DIAG  144

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANDSLDiagnostics. */
#define MDMOID_WAN_DSL_PROPRIETARY_DIAG  145

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANDSLDiagnostics.PeakLineNoise. */
#define MDMOID_WAN_DSL_DIAG_PLN  146

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANDSLDiagnostics.NonLinearity. */
#define MDMOID_WAN_DSL_DIAG_NON_LINEARITY  147

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}. */
#define MDMOID_WAN_CONN_DEVICE  148

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WANATMF4EndToEndLoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F4_END_TO_END_LOOPBACK_DIAG  149

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WANATMF4LoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F4_LOOPBACK_DIAG  150

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WANATMF5EndToEndLoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F5_END_TO_END_LOOPBACK_DIAG  151

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WANGPONLinkConfig. */
#define MDMOID_WAN_GPON_LINK_CFG  152

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WANEPONLinkConfig. */
#define MDMOID_WAN_EPON_LINK_CFG  153

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANDSLLinkConfig. */
#define MDMOID_WAN_DSL_LINK_CFG  154

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANDSLLinkConfig.X_5067F0_ATM_PARMS. */
#define MDMOID_WAN_DSL_ATM_PARAMS  155

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANATMF5LoopbackDiagnostics. */
#define MDMOID_WAN_ATM5_LOOPBACK_DIAG  156

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPTMLinkConfig. */
#define MDMOID_WAN_PTM_LINK_CFG  157

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANEthernetLinkConfig. */
#define MDMOID_WAN_ETH_LINK_CFG  158

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_L2tpAcLinkConfig. */
#define MDMOID_L2TP_AC_LINK_CONFIG  159

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WWANInterfaceConfig. */
#define MDMOID_WWAN_INTERFACE_CONFIG  160

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WWANInterfaceConfig.Stats. */
#define MDMOID_WWAN_INTERFACE_CONFIG_STATS  161

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WWANBudgetControl. */
#define MDMOID_WWAN_BUDGET_CONTROL  162

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WWANPingCheck. */
#define MDMOID_WWAN_PING_CHECK  163

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}. */
#define MDMOID_WAN_IP_CONN  164

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.PortMapping.{i}. */
#define MDMOID_WAN_IP_CONN_PORTMAPPING  165

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_5067F0_UPNPPortMappingRule.{i}. */
#define MDMOID_UPNP_IP_PORTMAPPING  166

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_5067F0_PortTriggering.{i}. */
#define MDMOID_WAN_IP_CONN_PORT_TRIGGERING  167

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_5067F0_FirewallException.{i}. */
#define MDMOID_WAN_IP_CONN_FIREWALL_EXCEPTION  168

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_5067F0_MacFilterObj. */
#define MDMOID_MAC_FILTER  169

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_5067F0_MacFilterObj.X_5067F0_MacFilterCfg.{i}. */
#define MDMOID_MAC_FILTER_CFG  170

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.Stats. */
#define MDMOID_WAN_IP_CONN_STATS  171

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_5067F0_EthernetWAN_MAC. */
#define MDMOID_IP_ETHERNET_WAN_MAC  172

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}. */
#define MDMOID_WAN_PPP_CONN  173

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.PortMapping.{i}. */
#define MDMOID_WAN_PPP_CONN_PORTMAPPING  174

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_5067F0_UPNPPortMappingRule.{i}. */
#define MDMOID_UPNP_PPP_PORTMAPPING  175

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_5067F0_PortTriggering.{i}. */
#define MDMOID_WAN_PPP_CONN_PORT_TRIGGERING  176

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_5067F0_FirewallException.{i}. */
#define MDMOID_WAN_PPP_CONN_FIREWALL_EXCEPTION  177

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.Stats. */
#define MDMOID_WAN_PPP_CONN_STATS  178

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_5067F0_EthernetWAN_MAC. */
#define MDMOID_PPP_ETHERNET_WAN_MAC  179

/*! \brief InternetGatewayDevice.X_5067F0_PortMappingEntry.{i}. */
#define MDMOID_WAN_CONN_PORTMAPPING  180

/*! \brief InternetGatewayDevice.X_5067F0_VcAutoHunt. */
#define MDMOID_VC_AUTO_HUNT  181

/*! \brief InternetGatewayDevice.X_5067F0_VcAutoHunt.VcHuntInfo.{i}. */
#define MDMOID_VC_HUNT_INFO  182

/*! \brief InternetGatewayDevice.X_5067F0_VcAutoHunt.VcHuntInfo.{i}.VcHuntRule.{i}. */
#define MDMOID_VC_HUNT_RULE  183

/*! \brief InternetGatewayDevice.X_5067F0_VlanAutoHunt. */
#define MDMOID_VLAN_AUTO_HUNT  184

/*! \brief InternetGatewayDevice.X_5067F0_VlanAutoHunt.VlanHuntInfo.{i}. */
#define MDMOID_VLAN_HUNT_INFO  185

/*! \brief InternetGatewayDevice.X_5067F0_VlanAutoHunt.HuntWAN.{i}.VlanHuntRule.{i}. */
#define MDMOID_VLAN_HUNT_RULE  186

/*! \brief InternetGatewayDevice.Layer3Forwarding. */
#define MDMOID_L3_FORWARDING  187

/*! \brief InternetGatewayDevice.Layer3Forwarding.Forwarding.{i}. */
#define MDMOID_L3_FORWARDING_ENTRY  188

/*! \brief InternetGatewayDevice.X_5067F0_IPv6Layer3Forwarding. */
#define MDMOID_I_PV6_L3_FORWARDING  189

/*! \brief InternetGatewayDevice.X_5067F0_IPv6Layer3Forwarding.IPv6Forwarding.{i}. */
#define MDMOID_I_PV6_L3_FORWARDING_ENTRY  190

/*! \brief InternetGatewayDevice.Services. */
#define MDMOID_SERVICES  191

/*! \brief InternetGatewayDevice.Services.StorageService.{i}. */
#define MDMOID_STORAGE_SERVICE  192

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.UserAccount.{i}. */
#define MDMOID_USER_ACCOUNT  193

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.Capabilites. */
#define MDMOID_CAPABILITES  194

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.NetInfo. */
#define MDMOID_NETWORK_INFO  195

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.NetworkServer. */
#define MDMOID_NETWORK_SERVER  196

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.PhysicalMedium.{i}. */
#define MDMOID_PHYSICAL_MEDIUM  197

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.LogicalVolume.{i}. */
#define MDMOID_LOGICAL_VOLUME  198

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.LogicalVolume.{i}.Folder.{i}. */
#define MDMOID_FOLDER  199

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}. */
#define MDMOID_VOICE  200

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}. */
#define MDMOID_VOICE_CALL_LIST  201

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.NewFlag. */
#define MDMOID_VOICE_CALL_NEW_FLAG  202

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.NumberOfMissedCalls. */
#define MDMOID_VOICE_CALL_NUMBER_OF_MISSED_CALLS  203

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.Number. */
#define MDMOID_VOICE_CALL_NUMBER  204

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.Name. */
#define MDMOID_VOICE_CALL_NAME  205

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.DateTime. */
#define MDMOID_VOICE_CALL_DATE_TIME  206

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.LineName. */
#define MDMOID_VOICE_CALL_LINE_NAME  207

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.LineId. */
#define MDMOID_VOICE_CALL_LINE_ID  208

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.CallType. */
#define MDMOID_VOICE_CALL_TYPE  209

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_InternalName.{i}. */
#define MDMOID_VOICE_INTERNAL_NAME_LIST  210

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_InternalName.{i}.TerminalNumber. */
#define MDMOID_VOICE_TERMINAL_NUMBER  211

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_InternalName.{i}.Name. */
#define MDMOID_VOICE_INTERNAL_NAME  212

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Contact.{i}. */
#define MDMOID_VOICE_CONTACT_LIST  213

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Contact.{i}.Name. */
#define MDMOID_VOICE_CONTACT_NAME  214

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Contact.{i}.FirstName. */
#define MDMOID_VOICE_CONTACT_FIRST_NAME  215

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Contact.{i}.ContactNumber. */
#define MDMOID_VOICE_CONTACT_NUMBER  216

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Contact.{i}.Melody. */
#define MDMOID_VOICE_CONTACT_MELODY  217

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Contact.{i}.LineId. */
#define MDMOID_VOICE_CONTACT_LINE_ID  218

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_SupportList.{i}. */
#define MDMOID_VOICE_DECT_SUPPORT_LIST  219

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities. */
#define MDMOID_VOICE_CAP  220

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.SIP. */
#define MDMOID_VOICE_CAP_SIP  221

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.MGCP. */
#define MDMOID_VOICE_CAP_MGCP  222

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.Codecs.{i}. */
#define MDMOID_VOICE_CAP_CODECS  223

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}. */
#define MDMOID_VOICE_PROF  224

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.ServiceProviderInfo. */
#define MDMOID_VOICE_PROF_PROVIDER  225

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.SIP. */
#define MDMOID_VOICE_PROF_SIP  226

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.SIP.EventSubscribe.{i}. */
#define MDMOID_VOICE_PROF_SIP_SUBSCRIBE  227

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.MGCP. */
#define MDMOID_VOICE_PROF_MGCP  228

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.RTP. */
#define MDMOID_VOICE_PROF_RTP  229

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.RTP.SRTP. */
#define MDMOID_VOICE_PROF_RTP_SRTP  230

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.NumberingPlan. */
#define MDMOID_VOICE_PROF_NUMBERING_PLAN  231

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.NumberingPlan.PrefixInfo.{i}. */
#define MDMOID_VOICE_PROF_NUMBERING_PLAN_PREFIX_INFO  232

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.FaxT38. */
#define MDMOID_VOICE_PROF_FAX_T38  233

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}. */
#define MDMOID_VOICE_LINE  234

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.SIP. */
#define MDMOID_VOICE_LINE_SIP  235

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.CallingFeatures. */
#define MDMOID_VOICE_LINE_CALLING_FEATURES  236

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.VoiceProcessing. */
#define MDMOID_VOICE_LINE_PROCESSING  237

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Codec. */
#define MDMOID_VOICE_LINE_CODEC  238

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Codec.List.{i}. */
#define MDMOID_VOICE_LINE_CODEC_LIST  239

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Session.{i}. */
#define MDMOID_VOICE_LINE_SESSION  240

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Stats. */
#define MDMOID_VOICE_LINE_STATS  241

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_LineSetting. */
#define MDMOID_VOICE_LINE_SETTING  242

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.LineName. */
#define MDMOID_VOICE_LINE_NAME  243

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.LineId. */
#define MDMOID_VOICE_LINE_DECT_LINE_ID  244

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.AttachedHandset. */
#define MDMOID_VOICE_LINE_ATTACHED_HANDSET  245

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.Melody. */
#define MDMOID_VOICE_LINE_MELODY  246

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.DialingPrefix. */
#define MDMOID_VOICE_LINE_DIALING_PREFIX  247

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.Volumn. */
#define MDMOID_VOICE_LINE_VOLUMN  248

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.BlockedNumber. */
#define MDMOID_VOICE_LINE_BLOCKED_NUMBER  249

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.MultiCallMode. */
#define MDMOID_VOICE_LINE_MULTI_CALL_MODE  250

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.IntrusionCall. */
#define MDMOID_VOICE_LINE_INTRUSION_CALL  251

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.CLIR. */
#define MDMOID_CLI_R  252

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.CallForwarding. */
#define MDMOID_VOICE_LINE_CALL_FORWARDING  253

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_PhyIntfMgn. */
#define MDMOID_VOICE_PHY_INTF_MGN  254

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_PhyIntfMgn.PhyInterface.{i}. */
#define MDMOID_VOICE_PHY_INTF  255

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_PhyIntfMgn.PhyInterface.{i}.X_5067F0_FXS.{i}. */
#define MDMOID_VOICE_PHY_INTF_FXS  256

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_PhyIntfMgn.PhyInterface.{i}.X_5067F0_FXO.{i}. */
#define MDMOID_VOICE_PHY_INTF_FXO  257

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.PhyInterface.{i}. */
#define MDMOID_PHY_INTF  258

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_PSTN.{i}. */
#define MDMOID_VOICE_PSTN  259

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Ntr. */
#define MDMOID_VOICE_NTR  260

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Ntr.History.{i}. */
#define MDMOID_VOICE_NTR_HISTORY  261

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface. */
#define MDMOID_VOICE_DECT_SYSTEM_SETTING  262

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.Handset.{i}. */
#define MDMOID_DECT_HANDSET  263

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.PINCode. */
#define MDMOID_VOICE_DECT_PIN_CODE  264

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.ClockMaster. */
#define MDMOID_VOICE_DECT_CLOCK_MASTER  265

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.ResetBase. */
#define MDMOID_VOICE_DECT_RESET_BASE  266

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.FirmwareVersion. */
#define MDMOID_VOICE_DECT_FIRMWARE_VERSION  267

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.HardwareVersion. */
#define MDMOID_VOICE_DECT_HARDWARE_VERSION  268

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.EEPROMVersion. */
#define MDMOID_EEPROM_VERSION  269

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Common. */
#define MDMOID_VOICE_COMMON  270

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_VoicePhoneBook.{i}. */
#define MDMOID_VOICE_PHONE_BOOK  271

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_FXO. */
#define MDMOID_VOICE_FXO  272

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_FXO.Port.{i}. */
#define MDMOID_VOICE_FXO_PORT  273

/*! \brief InternetGatewayDevice.X_5067F0_SnmpCfg. */
#define MDMOID_SNMP_CFG  274

/*! \brief InternetGatewayDevice.X_5067F0_EmailNotificationCfg.{i}. */
#define MDMOID_EMAIL_NOTIFICATION  275

/*! \brief InternetGatewayDevice.X_5067F0_SecDmzHostCfg. */
#define MDMOID_SEC_DMZ_HOST_CFG  276

/*! \brief InternetGatewayDevice.X_5067F0_AccessTimeRestriction.{i}. */
#define MDMOID_ACCESS_TIME_RESTRICTION  277

/*! \brief InternetGatewayDevice.X_5067F0_ParentalCtl.{i}. */
#define MDMOID_PARENTAL_CTL  278

/*! \brief InternetGatewayDevice.X_5067F0_ParentalCtl.{i}.X_5067F0_Url.{i}. */
#define MDMOID_URL  279

/*! \brief InternetGatewayDevice.X_5067F0_ParentalCtl.{i}.X_5067F0_NetworkService.{i}. */
#define MDMOID_PC_NETWORK_SRV  280

/*! \brief InternetGatewayDevice.X_5067F0_ParentalCtl.{i}.X_5067F0_NetworkService.{i}.X_5067F0_Service.{i}. */
#define MDMOID_PC_SERVICE  281

/*! \brief InternetGatewayDevice.X_5067F0_UrlFilterCfg. */
#define MDMOID_URL_FILTER_CFG  282

/*! \brief InternetGatewayDevice.X_5067F0_UrlFilterCfg.X_5067F0_UrlFilterListCfgObj.{i}. */
#define MDMOID_URL_FILTER_LIST  283

/*! \brief InternetGatewayDevice.X_5067F0_MacFilterObj. */
#define MDMOID_MSTC_MAC_FILTER  284

/*! \brief InternetGatewayDevice.X_5067F0_MacFilterObj.X_5067F0_MacFilterCfg.{i}. */
#define MDMOID_MSTC_MAC_FILTER_CFG  285

/*! \brief InternetGatewayDevice.X_5067F0_DnsMasqCfg. */
#define MDMOID_DNS_MASQ_CFG  286

/*! \brief InternetGatewayDevice.X_5067F0_DnsRouteEntry.{i}. */
#define MDMOID_DNS_ROUTE_ENTRY  287

/*! \brief InternetGatewayDevice.X_5067F0_DDnsCfg.{i}. */
#define MDMOID_D_DNS_CFG  288

/*! \brief InternetGatewayDevice.X_5067F0_IPPCfg. */
#define MDMOID_IPP_CFG  289

/*! \brief InternetGatewayDevice.X_5067F0_DLNA. */
#define MDMOID_DLNA  290

/*! \brief InternetGatewayDevice.X_5067F0_DLNA.DmsCfg. */
#define MDMOID_DMS_CFG  291

/*! \brief InternetGatewayDevice.X_5067F0_DebugPortMirroringCfg.{i}. */
#define MDMOID_WAN_DEBUG_PORT_MIRRORING_CFG  292

/*! \brief InternetGatewayDevice.X_5067F0_IPSecCfg.{i}. */
#define MDMOID_IP_SEC_CFG  293

/*! \brief InternetGatewayDevice.X_5067F0_CertificateCfg.{i}. */
#define MDMOID_CERTIFICATE_CFG  294

/*! \brief InternetGatewayDevice.X_5067F0_WapiCertificate. */
#define MDMOID_WAPI_CERTIFICATE  295

/*! \brief InternetGatewayDevice.X_5067F0_WapiCertificate.WapiAsCertificate. */
#define MDMOID_WAPI_AS_CERTIFICATE  296

/*! \brief InternetGatewayDevice.X_5067F0_WapiCertificate.WapiIssuedCertificate. */
#define MDMOID_WAPI_ISSUED_CERTIFICATE  297

/*! \brief InternetGatewayDevice.X_5067F0_NetworkConfig. */
#define MDMOID_NETWORK_CONFIG  298

/*! \brief InternetGatewayDevice.X_5067F0_InterfaceControl. */
#define MDMOID_INTERFACE_CONTROL  299

/*! \brief InternetGatewayDevice.X_5067F0_P8021agCfg. */
#define MDMOID_P8021AG_CFG  300

/*! \brief InternetGatewayDevice.X_5067F0_IGMPCfg. */
#define MDMOID_IGMP_CFG  301

/*! \brief InternetGatewayDevice.IGMP.GroupStats.{i}. */
#define MDMOID_GROUP_STATS  302

/*! \brief InternetGatewayDevice.IGMP.GroupStats.{i}.Total. */
#define MDMOID_GROUP_STATS_TOTAL  303

/*! \brief InternetGatewayDevice.IGMP.HostStats.{i}. */
#define MDMOID_HOST_STATS  304

/*! \brief InternetGatewayDevice.IGMP.HostStats.{i}.Total. */
#define MDMOID_HOST_STATS_TOTAL  305

/*! \brief InternetGatewayDevice.X_5067F0_IEEE8021xAuthenticationSupplicant.{i}. */
#define MDMOID_WAN8021_X  306

/*! \brief InternetGatewayDevice.X_5067F0_MLDCfg. */
#define MDMOID_MLD_CFG  307

/*! \brief InternetGatewayDevice.X_5067F0_IPTunnel.{i}. */
#define MDMOID_IP_TUNNEL  308

/*! \brief InternetGatewayDevice.X_5067F0_IPTunnel.{i}.V4inV6Tunnel.{i}. */
#define MDMOID_IPV4IN_IPV6_TUNNEL  309

/*! \brief InternetGatewayDevice.X_5067F0_IPTunnel.{i}.V6inV4Tunnel.{i}. */
#define MDMOID_IPV6IN_IPV4_TUNNEL  310

/*! \brief InternetGatewayDevice.X_ITU_T_ORG. */
#define MDMOID_ITU_T_ORG  311

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4. */
#define MDMOID_G_984_4  312

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement. */
#define MDMOID_EQUIPMENT_MANAGEMENT  313

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.OntG. */
#define MDMOID_ONT_G  314

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.Ont2G. */
#define MDMOID_ONT2_G  315

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.OntData. */
#define MDMOID_ONT_DATA  316

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.SoftwareImage.{i}. */
#define MDMOID_SOFTWARE_IMAGE  317

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.CardHolder.{i}. */
#define MDMOID_CARD_HOLDER  318

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.CircuitPack.{i}. */
#define MDMOID_CIRCUIT_PACK  319

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.PowerShedding.{i}. */
#define MDMOID_POWER_SHEDDING  320

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.PortMappingPackageG.{i}. */
#define MDMOID_PORT_MAPPING_PACKAGE_G  321

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement. */
#define MDMOID_ANI_MANAGEMENT  322

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.AniG.{i}. */
#define MDMOID_ANI_G  323

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.TCont.{i}. */
#define MDMOID_T_CONT  324

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemPortNetworkCtp.{i}. */
#define MDMOID_GEM_PORT_NETWORK_CTP  325

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemInterworkingTp.{i}. */
#define MDMOID_GEM_INTERWORKING_TP  326

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.MulticastGemInterworkingTp.{i}. */
#define MDMOID_MULTICAST_GEM_INTERWORKING_TP  327

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.MulticastGemInterworkingTp.{i}.MulticastAddressTable.{i}. */
#define MDMOID_GEM_INTERWORKING_TP_MULTICAST_ADDRESS_TABLE  328

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemPortPmHistoryData.{i}. */
#define MDMOID_GEM_PORT_PM_HISTORY_DATA  329

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GalEthernetProfile.{i}. */
#define MDMOID_GAL_ETHERNET_PROFILE  330

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GalEthernetPmHistoryData.{i}. */
#define MDMOID_GAL_ETHERNET_PM_HISTORY_DATA  331

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.FecPmHistoryData.{i}. */
#define MDMOID_FEC_PM_HISTORY_DATA  332

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices. */
#define MDMOID_LAYER2_DATA_SERVICES  333

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgeServiceProfile.{i}. */
#define MDMOID_MAC_BRIDGE_SERVICE_PROFILE  334

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_5067F0_MacBridgeServiceProfile.{i}. */
#define MDMOID_BC_MAC_BRIDGE_SERVICE_PROFILE  335

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgeConfigData.{i}. */
#define MDMOID_MAC_BRIDGE_CONFIG_DATA  336

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePmHistoryData.{i}. */
#define MDMOID_MAC_BRIDGE_PM_HISTORY_DATA  337

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortConfigData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_CONFIG_DATA  338

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortDesignationData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_DESIGNATION_DATA  339

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterTableData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_FILTER_TABLE_DATA  340

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterTableData.{i}.MacFilterTable.{i}. */
#define MDMOID_MAC_FILTER_TABLE  341

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterPreAssignTable.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_FILTER_PRE_ASSIGN_TABLE  342

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortBridgeTableData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_BRIDGE_TABLE_DATA  343

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortBridgeTableData.{i}.BridgeTable.{i}. */
#define MDMOID_BRIDGE_TABLE  344

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortPmHistoryData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_PM_HISTORY_DATA  345

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MapperServiceProfile.{i}. */
#define MDMOID_MAPPER_SERVICE_PROFILE  346

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_5067F0_MapperServiceProfile.{i}. */
#define MDMOID_BC_MAPPER_SERVICE_PROFILE  347

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.VlanTaggingFilterData.{i}. */
#define MDMOID_VLAN_TAGGING_FILTER_DATA  348

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.VlanTaggingOperationConfigurationData.{i}. */
#define MDMOID_VLAN_TAGGING_OPERATION_CONFIGURATION_DATA  349

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.ExtendedVlanTaggingOperationConfigurationData.{i}. */
#define MDMOID_EXTENDED_VLAN_TAGGING_OPERATION_CONFIGURATION_DATA  350

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.ExtendedVlanTaggingOperationConfigurationData.{i}.ReceivedFrameVlanTaggingOperationTable.{i}. */
#define MDMOID_RECEIVED_FRAME_VLAN_TAGGING_OPERATION_TABLE  351

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}. */
#define MDMOID_MULTICAST_OPERATIONS_PROFILE  352

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.DynamicAccessControlListTable.{i}. */
#define MDMOID_DYNAMIC_ACCESS_CONTROL_LIST_TABLE  353

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.StaticAccessControlListTable.{i}. */
#define MDMOID_STATIC_ACCESS_CONTROL_LIST_TABLE  354

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.LostGroupsListTable.{i}. */
#define MDMOID_LOST_GROUPS_LIST_TABLE  355

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberConfigInfo.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER_CONFIG_INFO  356

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberMonitor.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER_MONITOR  357

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberMonitor.{i}.ActiveGroupsListTable.{i}. */
#define MDMOID_ACTIVE_GROUPS_LIST_TABLE  358

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_5067F0_MulticastSubscriberMonitor.{i}. */
#define MDMOID_BC_MULTICAST_SUBSCRIBER_MONITOR  359

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_5067F0_MulticastSubscriberMonitor.{i}.MulticastSubscriber.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER  360

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.UpstreamEthernetFramePmHistoryData.{i}. */
#define MDMOID_UPSTREAM_ETHERNET_FRAME_PM_HISTORY_DATA  361

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.DownstreamEthernetFramePmHistoryData.{i}. */
#define MDMOID_DOWNSTREAM_ETHERNET_FRAME_PM_HISTORY_DATA  362

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices. */
#define MDMOID_LAYER3_DATA_SERVICES  363

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.IpHostConfigData.{i}. */
#define MDMOID_IP_HOST_CONFIG_DATA  364

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.X_5067F0_IpHostConfigData.{i}. */
#define MDMOID_BC_IP_HOST_CONFIG_DATA  365

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.IpHostPmHistoryData.{i}. */
#define MDMOID_IP_HOST_PM_HISTORY_DATA  366

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}. */
#define MDMOID_IPV6_HOST_CONFIG_DATA  367

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentAddressTable.{i}. */
#define MDMOID_IPV6_CURRENT_ADDRESS_TABLE  368

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentDefaultRouterTable.{i}. */
#define MDMOID_IPV6_CURRENT_DEFAULT_ROUTER_TABLE  369

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentDnsTable.{i}. */
#define MDMOID_IPV6_CURRENT_DNS_TABLE  370

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentOnlinkPrefixTable.{i}. */
#define MDMOID_IPV6_CURRENT_ONLINK_PREFIX_TABLE  371

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.X_BROADCOM_COM_Ipv6HostConfigData.{i}. */
#define MDMOID_BC_IPV6_HOST_CONFIG_DATA  372

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.TcpUdpConfigData.{i}. */
#define MDMOID_TCP_UDP_CONFIG_DATA  373

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices. */
#define MDMOID_ETHERNET_SERVICES  374

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.PptpEthernetUni.{i}. */
#define MDMOID_PPTP_ETHERNET_UNI  375

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA  376

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData2.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA2  377

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData3.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA3  378

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.VirtualEthernetInterfacePoint.{i}. */
#define MDMOID_VIRTUAL_ETHERNET_INTERFACE_POINT  379

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices. */
#define MDMOID_VOICE_SERVICES  380

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.PptpPotsUni.{i}. */
#define MDMOID_PPTP_POTS_UNI  381

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipUserData.{i}. */
#define MDMOID_SIP_USER_DATA  382

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipAgentConfigData.{i}. */
#define MDMOID_SIP_AGENT_CONFIG_DATA  383

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpVoiceCtp.{i}. */
#define MDMOID_VO_IP_VOICE_CTP  384

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpMediaProfile.{i}. */
#define MDMOID_VO_IP_MEDIA_PROFILE  385

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoiceServiceProfile.{i}. */
#define MDMOID_VOICE_SERVICE  386

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.RtpProfileData.{i}. */
#define MDMOID_RTP_PROFILE_DATA  387

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpAppServiceProfile.{i}. */
#define MDMOID_VO_IP_APP_SERVICE_PROFILE  388

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoiceFeatureAccessCodes.{i}. */
#define MDMOID_VOICE_FEATURE_ACCESS_CODES  389

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.NetworkDialPlanTable.{i}. */
#define MDMOID_NETWORK_DIAL_PLAN_TABLE  390

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.NetworkDialPlanTable.{i}.DialPlanTable.{i}. */
#define MDMOID_DIAL_PLAN_TABLE  391

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpLineStatus.{i}. */
#define MDMOID_VO_IP_LINE_STATUS  392

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.CallControlPmHistoryData.{i}. */
#define MDMOID_CALL_CONTROL_PM_HISTORY_DATA  393

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.RtpPmHistoryData.{i}. */
#define MDMOID_RTP_PM_HISTORY_DATA  394

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipAgentPmHistoryData.{i}. */
#define MDMOID_SIP_AGENT_PM_HISTORY_DATA  395

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipCallInitPmHistoryData.{i}. */
#define MDMOID_SIP_CALL_INIT_PM_HISTORY_DATA  396

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.MgcConfigData.{i}. */
#define MDMOID_MGC_CONFIG_DATA  397

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.MgcPmHistoryData.{i}. */
#define MDMOID_MGC_PM_HISTORY_DATA  398

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpConfigData.{i}. */
#define MDMOID_VO_IP_CONFIG_DATA  399

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices. */
#define MDMOID_MOCA_SERVICES  400

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.PptpMocaUni.{i}. */
#define MDMOID_PPTP_MOCA_UNI  401

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_5067F0_PptpMocaUni.{i}. */
#define MDMOID_BRCM_PPTP_MOCA_UNI  402

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_5067F0_MocaStatus.{i}. */
#define MDMOID_MOCA_STATUS  403

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_5067F0_MocaStats.{i}. */
#define MDMOID_MOCA_STATS  404

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaEthernetPmHistoryData.{i}. */
#define MDMOID_MOCA_ETHERNET_PM_HISTORY_DATA  405

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaInterfacePmHistoryData.{i}. */
#define MDMOID_MOCA_INTERFACE_PM_HISTORY_DATA  406

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaInterfacePmHistoryData.{i}.NodeTable.{i}. */
#define MDMOID_MOCA_INTERFACE_PM_HISTORY_DATA_NODE_TABLE  407

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement. */
#define MDMOID_TRAFFIC_MANAGEMENT  408

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.PriorityQueueG.{i}. */
#define MDMOID_PRIORITY_QUEUE_G  409

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.TrafficSchedulerG.{i}. */
#define MDMOID_TRAFFIC_SCHEDULER_G  410

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.GemTrafficDescriptor.{i}. */
#define MDMOID_GEM_TRAFFIC_DESCRIPTOR  411

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General. */
#define MDMOID_GENERAL  412

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.UniG.{i}. */
#define MDMOID_UNI_G  413

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.OltG. */
#define MDMOID_OLT_G  414

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.NetworkAddress.{i}. */
#define MDMOID_NETWORK_ADDRESS  415

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.AuthenticationSecurityMethod.{i}. */
#define MDMOID_AUTHENTICATION_SECURITY_METHOD  416

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.LargeString.{i}. */
#define MDMOID_LARGE_STRING  417

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.ThresholdData1.{i}. */
#define MDMOID_THRESHOLD_DATA1  418

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.ThresholdData2.{i}. */
#define MDMOID_THRESHOLD_DATA2  419

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.Omci. */
#define MDMOID_OMCI  420

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.TR069ManagementServer.{i}. */
#define MDMOID_TR069_MANAGEMENT_SERVER  421

/*! \brief InternetGatewayDevice.X_5067F0_OmciSystem. */
#define MDMOID_OMCI_SYSTEM  422

/*! \brief InternetGatewayDevice.X_5067F0_GponOmciStats. */
#define MDMOID_GPON_OMCI_STATS  423

/*! \brief InternetGatewayDevice.X_5067F0_ALG. */
#define MDMOID_ALG  424

/*! \brief InternetGatewayDevice.X_5067F0_PortMappingRule.{i}. */
#define MDMOID_PORTMAPPINGRULE  425

/*! \brief InternetGatewayDevice.X_5067F0_NAT_Session. */
#define MDMOID_NAT_SESSION  426

/*! \brief InternetGatewayDevice.X_5067F0_AddressMapping.{i}. */
#define MDMOID_ADDRESS_MAPPING  427

/*! \brief InternetGatewayDevice.X_5067F0_WlanNvram. */
#define MDMOID_WLAN_NVRAM  428

/*! \brief InternetGatewayDevice.X_CT_OAM. */
#define MDMOID_CTOAM  429

/*! \brief InternetGatewayDevice.X_CT_OAM.IADInfo. */
#define MDMOID_OAMIAD_INFO  430

/*! \brief InternetGatewayDevice.X_CT_OAM.GlobalParameterConfig. */
#define MDMOID_OAM_GLB_PARAM_CFG  431

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPParameterConfig. */
#define MDMOID_OAMSIP_PARAM_CFG  432

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPUserParameterConfig. */
#define MDMOID_OAMSIP_USR_PARAM_CFG  433

/*! \brief InternetGatewayDevice.X_CT_OAM.FAXModemConfig. */
#define MDMOID_OAMFAXMD_CFG  434

/*! \brief InternetGatewayDevice.X_CT_OAM.POTSStatus. */
#define MDMOID_OAMPOTS_STS  435

/*! \brief InternetGatewayDevice.X_CT_OAM.IADOperation. */
#define MDMOID_OAMIAD_OP  436

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPDigitMap. */
#define MDMOID_OAMSIP_DGT_MP  437

/*! \brief InternetGatewayDevice.SoftwareModules. */
#define MDMOID_SW_MODULES  438

/*! \brief InternetGatewayDevice.SoftwareModules.ExecutionUnit.{i}. */
#define MDMOID_EU  439

/*! \brief InternetGatewayDevice.SoftwareModules.ExecutionUnit.{i}.Extensions. */
#define MDMOID_EXTENSIONS  440

/*! \brief InternetGatewayDevice.SoftwareModules.ExecEnv.{i}. */
#define MDMOID_EXEC_ENV  441

/*! \brief InternetGatewayDevice.SoftwareModules.DeploymentUnit.{i}. */
#define MDMOID_DU  442

/*! \brief InternetGatewayDevice.Device. */
#define MDMOID_DEVICE  443

/*! \brief InternetGatewayDevice.Device.Optical. */
#define MDMOID_DEVICE_OPTICAL  444

/*! \brief InternetGatewayDevice.Device.Optical.Interface.{i}. */
#define MDMOID_OPTICAL_INTERFACE  445

/*! \brief InternetGatewayDevice.Device.Optical.Interface.{i}.Stats. */
#define MDMOID_OPTICAL_INTERFACE_STATS  446

/*! \brief InternetGatewayDevice.X_5067F0_FirewallObj. */
#define MDMOID_MSTC_FIREWALL  447

/*! \brief InternetGatewayDevice.X_5067F0_AccessControlObj.{i}. */
#define MDMOID_MSTC_ACL  448

/*! \brief InternetGatewayDevice.X_5067F0_Schedule.{i}. */
#define MDMOID_SCHEDULE  449

/*! \brief InternetGatewayDevice.X_5067F0_AutoScheduleObj. */
#define MDMOID_MSTC_AUTO_SCHEDULE  450

/*! \brief InternetGatewayDevice.X_5067F0_ServiceObj.{i}. */
#define MDMOID_MSTC_SERVICE  451

/*! \brief InternetGatewayDevice.X_5067F0_ServiceObj.{i}.X_5067F0_ProtocolCfg.{i}. */
#define MDMOID_MSTC_PROTO_CFG  452

/*! \brief InternetGatewayDevice.X_5067F0_AccessServiceCfg. */
#define MDMOID_MSTC_ACCESS_SERVICE  453

/*! \brief InternetGatewayDevice.X_5067F0_WebUi. */
#define MDMOID_WEB_UI  454

/*! \brief InternetGatewayDevice.X_5067F0_Hosts.{i}. */
#define MDMOID_LAN_ZY_HOST_ENTRY  455

/*! \brief InternetGatewayDevice.X_5067F0_CBTFirewallObj. */
#define MDMOID_MSTC_CBT_FIREWALL  456

/*! \brief maximum OID value */
#define MDM_MAX_OID 456



#endif /* __MDM_OBJECTID_H__ */
