/*******************************************************************************
 *
 * FILENAME       : icf_icf_map_trace_id.h
 *
 * DESCRIPTION    : This file contains the trace ids that shall be used within 
 *                  the IMS client framework.
 *                     
 * Revision History :
 * 
 * DATE         NAME                REFERENCE       REASON
 * -----------  -------------       ------------    --------------
 * 09-Aug-2004  Rohit Aggarwal                      Initial
 * 02-Feb-2006  Amit Sharma                         CFG merged with ICF 2.0
 * 10-Mar-2006  Amit Sharma                         ICF merging with ICF2.0
 * 
 * Copyright (c) 2006, Aricent .
 ******************************************************************************/

#ifndef __ICF_ICF_MAP_TRACE_ID_H__
#define __ICF_ICF_MAP_TRACE_ID_H__


#include "icf_trace_id.h"
/* Determine if a C++ compiler is being used.
 * If so, ensure that standard
 * C is used to process the header information.
 * */

#ifdef __cplusplus

/* Yes, C++ compiler is present.
 * Use standard C.
 * */

extern "C"
{
#endif /* __cplusplus */


/******************** STANDARD INCLUDE FILES *****************************/
#define	ICF_TRACE_UNDEFINED	    ICF_TRACE_UNDEFINED
#define	ICF_TRACE_NORMAL_START	    ICF_TRACE_NORMAL_START
#define	ICF_TRACE_MODULE_ENTRY	    ICF_TRACE_MODULE_ENTRY
#define	ICF_TRACE_MODULE_EXIT	    ICF_TRACE_MODULE_EXIT
#define	ICF_TRACE_FUNCTION_ENTRY	    ICF_TRACE_FUNCTION_ENTRY
#define	ICF_TRACE_FUNCTION_EXIT	    ICF_TRACE_FUNCTION_EXIT
#define	ICF_TRACE_SETUP_RECVD_FRM_PA	    ICF_TRACE_SETUP_RECVD_FRM_PA
#define	ICF_TRACE_FSM_TRIGGERED	    ICF_TRACE_FSM_TRIGGERED
#define	ICF_TRACE_CALL_STATUS_PA_CLR	    ICF_TRACE_CALL_STATUS_PA_CLR
#define	ICF_TRACE_CALL_STATUS_MM_CLR	    ICF_TRACE_CALL_STATUS_MM_CLR
#define	ICF_TRACE_CALL_STATUS_NW_CLR	    ICF_TRACE_CALL_STATUS_NW_CLR
#define	ICF_TRACE_CALL_STATUS_ALL_CLR	    ICF_TRACE_CALL_STATUS_ALL_CLR
#define	ICF_TRACE_REL_TYPE_PA_INIT	    ICF_TRACE_REL_TYPE_PA_INIT
#define	ICF_TRACE_REL_TYPE_MM_INIT	    ICF_TRACE_REL_TYPE_MM_INIT
#define	ICF_TRACE_REL_TYPE_NW_INIT	    ICF_TRACE_REL_TYPE_NW_INIT
#define	ICF_TRACE_REL_TYPE_TIMER_INIT	    ICF_TRACE_REL_TYPE_TIMER_INIT
#define	ICF_TRACE_REL_TYPE_INT_ERR	    ICF_TRACE_REL_TYPE_INT_ERR
#define	ICF_TRACE_CALL_MUTE_SET	    ICF_TRACE_CALL_MUTE_SET
#define	ICF_TRACE_CALL_MUTE_RESET	    ICF_TRACE_CALL_MUTE_RESET
#define	ICF_TRACE_CALL_DIR	    ICF_TRACE_CALL_DIR
#define	ICF_TRACE_MEDIA_SETUP_TYPE	    ICF_TRACE_MEDIA_SETUP_TYPE
#define	ICF_TRACE_MEDIA_COMMITTED	    ICF_TRACE_MEDIA_COMMITTED
#define	ICF_TRACE_SDP_IN_PEER_MSG	    ICF_TRACE_SDP_IN_PEER_MSG
#define	ICF_TRACE_PREVIOUS_STATE	    ICF_TRACE_PREVIOUS_STATE
#define	ICF_TRACE_SET_PREVIOUS_STATE	    ICF_TRACE_SET_PREVIOUS_STATE
#define	ICF_TRACE_CURRENT_STATE	    ICF_TRACE_CURRENT_STATE
#define	ICF_TRACE_SET_CURRENT_STATE	    ICF_TRACE_SET_CURRENT_STATE
#define	ICF_TRACE_NEXT_STATE	    ICF_TRACE_NEXT_STATE
#define	ICF_TRACE_SET_NEXT_STATE	    ICF_TRACE_SET_NEXT_STATE
#define	ICF_TRACE_MEDIA_MODE	    ICF_TRACE_MEDIA_MODE
#define	ICF_TRACE_SET_MEDIA_MODE	    ICF_TRACE_SET_MEDIA_MODE
#define	ICF_TRACE_SET_MODE_TO_BE_APP	    ICF_TRACE_SET_MODE_TO_BE_APP
#define	ICF_TRACE_SET_RELEASE_CAUSE	    ICF_TRACE_SET_RELEASE_CAUSE
#define	ICF_TRACE_MEDIA_ONGOING	    ICF_TRACE_MEDIA_ONGOING
#define	ICF_TRACE_SET_MEDIA_ONGOING	    ICF_TRACE_SET_MEDIA_ONGOING
#define	ICF_TRACE_SIG_ONGOING	    ICF_TRACE_SIG_ONGOING
#define	ICF_TRACE_SET_SIG_ONGOING	    ICF_TRACE_SET_SIG_ONGOING
#define	ICF_TRACE_ONGOING_EVENT	    ICF_TRACE_ONGOING_EVENT
#define	ICF_TRACE_SET_ONGOING_EVENT	    ICF_TRACE_SET_ONGOING_EVENT
#define	ICF_TRACE_INBAND_INFO	    ICF_TRACE_INBAND_INFO
#define	ICF_TRACE_EVENT_PA_CONNECT	    ICF_TRACE_EVENT_PA_CONNECT
#define	ICF_TRACE_EVENT_PA_TERM_REQ	    ICF_TRACE_EVENT_PA_TERM_REQ
#define	ICF_TRACE_EVENT_MM_ERR_IND	    ICF_TRACE_EVENT_MM_ERR_IND
#define	ICF_TRACE_EVENT_OFFER_CHANGE	    ICF_TRACE_EVENT_OFFER_CHANGE
#define	ICF_TRACE_EVENT_INT_ERR	    ICF_TRACE_EVENT_INT_ERR
#define	ICF_TRACE_TIMER_EXPIRED	    ICF_TRACE_TIMER_EXPIRED
#define	ICF_TRACE_SEND_MMI_REQ	    ICF_TRACE_SEND_MMI_REQ
#define	ICF_TRACE_DMS_REQ_PAYLOAD	    ICF_TRACE_DMS_REQ_PAYLOAD
#define	ICF_TRACE_MMS_REQ_PAYLOAD	    ICF_TRACE_MMS_REQ_PAYLOAD
#define	ICF_TRACE_PRACK_REQD	    ICF_TRACE_PRACK_REQD
#define	ICF_TRACE_MEDIA_TO_BE_SENT	    ICF_TRACE_MEDIA_TO_BE_SENT
#define	ICF_TRACE_EVENT_CALL_MUTE	    ICF_TRACE_EVENT_CALL_MUTE
#define	ICF_TRACE_EVENT_CALL_UNMUTE	    ICF_TRACE_EVENT_CALL_UNMUTE
#define	ICF_TRACE_CALL_FAIL_NO_SDP	    ICF_TRACE_CALL_FAIL_NO_SDP
#define	ICF_TRACE_START_TIMER	    ICF_TRACE_START_TIMER
#define	ICF_TRACE_STOP_TIMER	    ICF_TRACE_STOP_TIMER
#define	ICF_INTERFACE_FAILURE	    ICF_INTERFACE_FAILURE
#define	ICF_PA_INCOMING_CALL_IND	    ICF_PA_INCOMING_CALL_IND
#define	ICF_PA_ALERT_USER_IND	    ICF_PA_ALERT_USER_IND
#define	ICF_PA_CONNECT_IND	    ICF_PA_CONNECT_IND
#define	ICF_PA_CALL_TERM_IND	    ICF_PA_CALL_TERM_IND
#define	ICF_PA_TERMINATE_CALL_RESP	    ICF_PA_TERMINATE_CALL_RESP
#define	ICF_PA_CALL_REDIRECTION_IND	    ICF_PA_CALL_REDIRECTION_IND
#define	ICF_PA_CALL_HOLD_IND	    ICF_PA_CALL_HOLD_IND
#define	ICF_PA_CALL_RESUME_IND	    ICF_PA_CALL_RESUME_IND
#define	ICF_PA_MEDIA_CONNECT	    ICF_PA_MEDIA_CONNECT
#define	ICF_UNEXPECTED_EVENT	    ICF_UNEXPECTED_EVENT
#define	ICF_DIVERSION_INFO_VALIDATION_FAILED	    ICF_DIVERSION_INFO_VALIDATION_FAILED
#define	ICF_TRANSPORT_ADDRESS	    ICF_TRANSPORT_ADDRESS
#define	ICF_TRACE_INIT_COMPLETE_STATUS	    ICF_TRACE_INIT_COMPLETE_STATUS
#define	ICF_TRACE_PARAM_VALIDITY	    ICF_TRACE_PARAM_VALIDITY
#define	ICF_TRACE_SRVC_TRIG_STAT_RET	    ICF_TRACE_SRVC_TRIG_STAT_RET
#define	ICF_PA_CALL_TERM_IND_NO_CTX	    ICF_PA_CALL_TERM_IND_NO_CTX
#define	ICF_TRACE_MEDIA_MODIFY_SENT	    ICF_TRACE_MEDIA_MODIFY_SENT
#define	ICF_MSG_PROC_STATUS	    ICF_MSG_PROC_STATUS
#define	ICF_MSG_PROC_RECV_INT_MSG	    ICF_MSG_PROC_RECV_INT_MSG
#define	ICF_MSG_PROC_ACTION_RESULT	    ICF_MSG_PROC_ACTION_RESULT
#define	ICF_MSG_PROC_FIELD_DATA	    ICF_MSG_PROC_FIELD_DATA
#define	ICF_MSG_PROC_FIELD_TYPE	    ICF_MSG_PROC_FIELD_TYPE
#define	ICF_MSG_PROC_PRESENCE_FIELD	    ICF_MSG_PROC_PRESENCE_FIELD
#define	ICF_MSG_PROC_VALUE_ACTION	    ICF_MSG_PROC_VALUE_ACTION
#define	ICF_MSG_PROC_ACTION	    ICF_MSG_PROC_ACTION
#define	ICF_TRACE_NORMAL_END	    ICF_TRACE_NORMAL_END
#define	ICF_TRACE_ERROR_START	    ICF_TRACE_ERROR_START
#define	ICF_TRACE_MEM_ALLOC_FAILURE	    ICF_TRACE_MEM_ALLOC_FAILURE
#define	ICF_TRACE_MEM_FREE_FAILURE	    ICF_TRACE_MEM_FREE_FAILURE
#define	ICF_TRACE_TMR_START_FAILURE	    ICF_TRACE_TMR_START_FAILURE
#define	ICF_TRACE_TMR_STOP_FAILURE	    ICF_TRACE_TMR_STOP_FAILURE
#define	ICF_TRACE_INVALID_API_ID	    ICF_TRACE_INVALID_API_ID
#define	ICF_TRACE_ERROR_END	    ICF_TRACE_ERROR_END
#define	ICF_TRACE_ASSERT_FAILED	    ICF_TRACE_ASSERT_FAILED
#define	ICF_TRACE_CALL_HOLD_RECVD	    ICF_TRACE_CALL_HOLD_RECVD
#define	ICF_TRACE_CALL_HOLD_SUCC_RESP	    ICF_TRACE_CALL_HOLD_SUCC_RESP
#define	ICF_TRACE_CALL_RESUME_RECVD	    ICF_TRACE_CALL_RESUME_RECVD
#define	ICF_TRACE_MMS_SEND	    ICF_TRACE_MMS_SEND
#define	ICF_TRACE_HOLD_REQ_TO_NW	    ICF_TRACE_HOLD_REQ_TO_NW
#define	ICF_TRACE_HLD_SUCC_FROM_NW	    ICF_TRACE_HLD_SUCC_FROM_NW
#define	ICF_TRACE_RSM_REQ_TO_NW	    ICF_TRACE_RSM_REQ_TO_NW
#define	ICF_TRACE_RSM_RESP_FROM_NW	    ICF_TRACE_RSM_RESP_FROM_NW
#define	ICF_TRACE_HLD_FAIL_FROM_NW	    ICF_TRACE_HLD_FAIL_FROM_NW
#define	ICF_TRACE_REQ_CANCEL_SEND	    ICF_TRACE_REQ_CANCEL_SEND
#define	ICF_TRACE_CANCEL_RESP_RECV	    ICF_TRACE_CANCEL_RESP_RECV
#define	ICF_TRACE_MED_ERR_DMS_IND	    ICF_TRACE_MED_ERR_DMS_IND
#define	ICF_TRACE_MED_ERR_MMS_FAIL	    ICF_TRACE_MED_ERR_MMS_FAIL
#define	ICF_TRACE_CHR_TIMER_EXPD	    ICF_TRACE_CHR_TIMER_EXPD
#define	ICF_TRACE_RACE_TIMER_EXPD	    ICF_TRACE_RACE_TIMER_EXPD
#define	ICF_TRACE_ST_PROC_SIG_RCVD	    ICF_TRACE_ST_PROC_SIG_RCVD
#define	ICF_TRACE_ST_PROC_MED_RCVD	    ICF_TRACE_ST_PROC_MED_RCVD
#define	ICF_TRACE_CALL_RELEASED	    ICF_TRACE_CALL_RELEASED
#define	ICF_TRACE_CALL_ALREADY_HOLD	    ICF_TRACE_CALL_ALREADY_HOLD
#define	ICF_TRACE_SERVICE_TERM_NORMAL	    ICF_TRACE_SERVICE_TERM_NORMAL
#define	ICF_TRACE_SERVICE_TERM_ERROR	    ICF_TRACE_SERVICE_TERM_ERROR
#define	ICF_TRACE_CALL_REMOTE_HOLD	    ICF_TRACE_CALL_REMOTE_HOLD
#define	ICF_TRACE_SET_ST_PROC_SIG	    ICF_TRACE_SET_ST_PROC_SIG
#define	ICF_TRACE_SSA_FAIL_RESP	    ICF_TRACE_SSA_FAIL_RESP
#define	ICF_TRACE_SSA_SUCC_RESP	    ICF_TRACE_SSA_SUCC_RESP
#define	ICF_TRACE_CHR_STATE	    ICF_TRACE_CHR_STATE
#define	ICF_TRACE_CHR_EVENT	    ICF_TRACE_CHR_EVENT
#define	ICF_TRACE_ONGOING_ACT	    ICF_TRACE_ONGOING_ACT
#define	ICF_TRACE_PENDING_EVT	    ICF_TRACE_PENDING_EVT
#define	ICF_TRACE_MMI_FAIL_RESP	    ICF_TRACE_MMI_FAIL_RESP
#define	ICF_TRACE_MMI_SUCC_RESP	    ICF_TRACE_MMI_SUCC_RESP
#define	ICF_TRACE_SET_ST_PROC_MED	    ICF_TRACE_SET_ST_PROC_MED
#define	ICF_TRACE_MED_ONGOING	    ICF_TRACE_MED_ONGOING
#define	ICF_TRACE_CALL_ALRADY_ACTIVE	    ICF_TRACE_CALL_ALRADY_ACTIVE
#define	ICF_TRACE_MMS_SUCC_RESP	    ICF_TRACE_MMS_SUCC_RESP
#define	ICF_TRACE_CURR_RET_STATUS	    ICF_TRACE_CURR_RET_STATUS
#define	ICF_TRACE_GET_GLB_DATA_FAILED	    ICF_TRACE_GET_GLB_DATA_FAILED
#define	ICF_TRACE_API_RECVD	    ICF_TRACE_API_RECVD
#define	ICF_TRACE_SVC_CONT_RECVD	    ICF_TRACE_SVC_CONT_RECVD
#define	ICF_TRACE_SVC_END_RECVD	    ICF_TRACE_SVC_END_RECVD
#define	ICF_TRACE_SL_CTX_FREED	    ICF_TRACE_SL_CTX_FREED
#define	ICF_TRACE_CH_SUCCESS_STATUS	    ICF_TRACE_CH_SUCCESS_STATUS
#define	ICF_TRACE_CR_SUCCESS_STATUS	    ICF_TRACE_CR_SUCCESS_STATUS
#define	ICF_TRACE_CALL_RELEASE_FORWARDED	    ICF_TRACE_CALL_RELEASE_FORWARDED
#define	ICF_TRACE_SVC_ERR_IND_STATUS	    ICF_TRACE_SVC_ERR_IND_STATUS
#define	ICF_TRACE_CH_REQ_STATUS	    ICF_TRACE_CH_REQ_STATUS
#define	ICF_TRACE_CR_REQ_STATUS	    ICF_TRACE_CR_REQ_STATUS
#define	ICF_TRACE_START_PROC_MEDIA_STATUS	    ICF_TRACE_START_PROC_MEDIA_STATUS
#define	ICF_TRACE_START_PROC_SIG_STATUS	    ICF_TRACE_START_PROC_SIG_STATUS
#define	ICF_TRACE_SIG_EVENTS_REQ_STATUS	    ICF_TRACE_SIG_EVENTS_REQ_STATUS
#define	ICF_TRACE_MEDIA_EVENTS_REQ_STATUS	    ICF_TRACE_MEDIA_EVENTS_REQ_STATUS
#define	ICF_TRACE_ALL_SVC_ENDED	    ICF_TRACE_ALL_SVC_ENDED
#define	ICF_TRACE_INV_API_RECVD	    ICF_TRACE_INV_API_RECVD
#define	ICF_TRACE_SEND_FAILURE_TO_PA	    ICF_TRACE_SEND_FAILURE_TO_PA
#define	ICF_TRACE_SEND_FAILURE_TO_SL	    ICF_TRACE_SEND_FAILURE_TO_SL
#define	ICF_TRACE_FAILURE_RESP_SEND_FAIL	    ICF_TRACE_FAILURE_RESP_SEND_FAIL
#define	ICF_TRACE_GET_HANDLER_SL	    ICF_TRACE_GET_HANDLER_SL
#define	ICF_TRACE_SVC_REQ_ONE_CALL	    ICF_TRACE_SVC_REQ_ONE_CALL
#define	ICF_TRACE_SVC_REQ_TWO_CALLS	    ICF_TRACE_SVC_REQ_TWO_CALLS
#define	ICF_TRACE_RNW_INV_STATE	    ICF_TRACE_RNW_INV_STATE
#define	ICF_TRACE_SVC_REQ_VALID	    ICF_TRACE_SVC_REQ_VALID
#define	ICF_TRACE_SVC_CTX_CREATE	    ICF_TRACE_SVC_CTX_CREATE
#define	ICF_TRACE_SL_CTX_CREATE	    ICF_TRACE_SL_CTX_CREATE
#define	ICF_TRACE_SVC_REQ_INVALID	    ICF_TRACE_SVC_REQ_INVALID
#define	ICF_TRACE_MSG_ROUTING_FAILED	    ICF_TRACE_MSG_ROUTING_FAILED
#define	ICF_TRACE_MSG_ROUTING_PROGRESS	    ICF_TRACE_MSG_ROUTING_PROGRESS
#define	ICF_TRACE_CALL_ID_EXTRACTED	    ICF_TRACE_CALL_ID_EXTRACTED
#define	ICF_TRACE_GET_CALL_CTX	    ICF_TRACE_GET_CALL_CTX
#define	ICF_TRACE_INIT_COMPLETE_RECVD	    ICF_TRACE_INIT_COMPLETE_RECVD
#define	ICF_TRACE_INIT_COMPLETE_SUCCESSFUL	    ICF_TRACE_INIT_COMPLETE_SUCCESSFUL
#define	ICF_TRACE_MODIFY_USER_ADDRESS_RECVD	    ICF_TRACE_MODIFY_USER_ADDRESS_RECVD
#define	ICF_TRACE_PROCESS_MODIFY_USER_BLK	    ICF_TRACE_PROCESS_MODIFY_USER_BLK
#define	ICF_TRACE_REGISTRATION_FSM_TRIGGERED	    ICF_TRACE_REGISTRATION_FSM_TRIGGERED
#define	ICF_TRACE_MODIFY_USER_ROLLBACK	    ICF_TRACE_MODIFY_USER_ROLLBACK
#define	ICF_TRACE_MODIFY_REG_ADDRESS_RECVD	    ICF_TRACE_MODIFY_REG_ADDRESS_RECVD
#define	ICF_TRACE_PROCESS_MODIFY_REG_BLK	    ICF_TRACE_PROCESS_MODIFY_REG_BLK
#define	ICF_TRACE_MODIFY_REG_ROLLBACK	    ICF_TRACE_MODIFY_REG_ROLLBACK
#define	ICF_TRACE_MODIFY_DURATION_RECVD	    ICF_TRACE_MODIFY_DURATION_RECVD
#define	ICF_TRACE_PROCESS_MODIFY_DUR_BLK	    ICF_TRACE_PROCESS_MODIFY_DUR_BLK
#define	ICF_TRACE_MODIFY_DUR_ROLLBACK	    ICF_TRACE_MODIFY_DUR_ROLLBACK
#define	ICF_TRACE_INVALID_STATE_EVENT	    ICF_TRACE_INVALID_STATE_EVENT
#define	ICF_TRACE_RETRY_TIMER_EXPIRY	    ICF_TRACE_RETRY_TIMER_EXPIRY
#define	ICF_TRACE_REG_TIMER_EXPIRY	    ICF_TRACE_REG_TIMER_EXPIRY
#define	ICF_TRACE_REG_REATT_TIMER_EXPIRY	    ICF_TRACE_REG_REATT_TIMER_EXPIRY
#define	ICF_TRACE_SENDING_REG_REQUEST	    ICF_TRACE_SENDING_REG_REQUEST
#define	ICF_TRACE_SENDING_DEREG_REQUEST	    ICF_TRACE_SENDING_DEREG_REQUEST
#define	ICF_CALL_CTX_ALLOCATE	    ICF_CALL_CTX_ALLOCATE
#define	ICF_SRVC_CTX_ALLOCATE	    ICF_SRVC_CTX_ALLOCATE
#define	ICF_CALL_CTX_FOUND	    ICF_CALL_CTX_FOUND
#define	ICF_SRVC_CTX_FOUND	    ICF_SRVC_CTX_FOUND
#define	ICF_CALL_CTX_FREED	    ICF_CALL_CTX_FREED
#define ICF_DBM_BLOCK_ALLOCATED	ICF_DBM_BLOCK_ALLOCATED
#define ICF_DBM_BLOCK_DEALLOCATED	ICF_DBM_BLOCK_DEALLOCATED
#define	ICF_TRACE_MMI_START	    ICF_TRACE_MMI_START
#define	ICF_EVENT_RECVD	    ICF_EVENT_RECVD
#define	ICF_TRACE_API_SEND	    ICF_TRACE_API_SEND
#define	ICF_TRACE_MMS_FOR_CODEC_CHANGE	    ICF_TRACE_MMS_FOR_CODEC_CHANGE
#define	ICF_TRACE_MEDIA_COMMITED	    ICF_TRACE_MEDIA_COMMITED
#define	ICF_TRACE_MEDIA_NOT_COMMITED	    ICF_TRACE_MEDIA_NOT_COMMITED
#define	ICF_TRACE_DMS_NOT_FORCEFUL	    ICF_TRACE_DMS_NOT_FORCEFUL
#define	ICF_TRACE_FORCEFUL_DMS	    ICF_TRACE_FORCEFUL_DMS
#define	ICF_TRACE_FAILURE_RESP	    ICF_TRACE_FAILURE_RESP
#define	ICF_TRACE_SUCCESS_RESP	    ICF_TRACE_SUCCESS_RESP
#define	ICF_TRACE_CC_AWT_DMS	    ICF_TRACE_CC_AWT_DMS
#define	ICF_TRACE_MEDIA_ESTABLISHED	    ICF_TRACE_MEDIA_ESTABLISHED
#define	ICF_TRACE_MEDIA_NOT_ESTABLISHED	    ICF_TRACE_MEDIA_NOT_ESTABLISHED
#define	ICF_TRACE_MODIFY_FOR_CODEC_CHANGE_SET	    ICF_TRACE_MODIFY_FOR_CODEC_CHANGE_SET
#define	ICF_TRACE_RESTORATION_IN_PROGRESS_SET	    ICF_TRACE_RESTORATION_IN_PROGRESS_SET
#define	ICF_TRACE_MMS_FOR_MODE_CHANGE	    ICF_TRACE_MMS_FOR_MODE_CHANGE
#define	ICF_TRACE_MMS_WITH_REMOTE_SDP	    ICF_TRACE_MMS_WITH_REMOTE_SDP
#define	ICF_TRACE_MODIFY_FOR_REMOTE_MEDIA_APPLICATION_SET	    ICF_TRACE_MODIFY_FOR_REMOTE_MEDIA_APPLICATION_SET
#define	ICF_TRACE_CALL_INCOMING_FS	    ICF_TRACE_CALL_INCOMING_FS
#define	ICF_TRACE_FAILURE_TO_SEND	    ICF_TRACE_FAILURE_TO_SEND
#define	ICF_TRACE_FAILURE_BY_CM	    ICF_TRACE_FAILURE_BY_CM
#define	ICF_TRACE_FAILURE_TO_PROCESS_MSG	    ICF_TRACE_FAILURE_TO_PROCESS_MSG
#define	ICF_TRACE_FAILURE_BY_DBM	    ICF_TRACE_FAILURE_BY_DBM
#define	ICF_TRACE_UNEXPECTED_EVENT	    ICF_TRACE_UNEXPECTED_EVENT
#define	ICF_MMI_TRACE_CURRENT_STATE	    ICF_MMI_TRACE_CURRENT_STATE
#define	ICF_TRACE_MMS_FOR_REMOTE_MEDIA_CHANGE	    ICF_TRACE_MMS_FOR_REMOTE_MEDIA_CHANGE
#define	ICF_TRACE_MMS_FOR_REMOTE_MEDIA_APPLICATION	    ICF_TRACE_MMS_FOR_REMOTE_MEDIA_APPLICATION
#define	ICF_TRACE_NUM_OF_LOCAL_CODECS	    ICF_TRACE_NUM_OF_LOCAL_CODECS
#define	ICF_TRACE_NEGOTIATION_FAILURE	    ICF_TRACE_NEGOTIATION_FAILURE
#define	ICF_TRACE_HDR_SEND	    ICF_TRACE_HDR_SEND
#define	ICF_TRACE_GCL_DATA_SEND	    ICF_TRACE_GCL_DATA_SEND
#define	ICF_TRACE_NUM_OF_CODECS	    ICF_TRACE_NUM_OF_CODECS
#define	ICF_TRACE_CODEC	    ICF_TRACE_CODEC
#define	ICF_TRACE_MMS_DATA_SEND	    ICF_TRACE_MMS_DATA_SEND
#define	ICF_TRACE_MMS_SDP_SEND	    ICF_TRACE_MMS_SDP_SEND
#define	ICF_TRACE_MMS_ADDR_SEND	    ICF_TRACE_MMS_ADDR_SEND
#define	ICF_TRACE_COMMIT_DATA_SEND	    ICF_TRACE_COMMIT_DATA_SEND
#define	ICF_TRACE_CALL_OTG_OR_INC_NFS	    ICF_TRACE_CALL_OTG_OR_INC_NFS
#define	ICF_TRACE_CMS_DATA_SEND	    ICF_TRACE_CMS_DATA_SEND
#define	ICF_TRACE_LOCAL_AUDIO_CODEC_LIST	    ICF_TRACE_LOCAL_AUDIO_CODEC_LIST
#define	ICF_TRACE_REMOTE_SDP	    ICF_TRACE_REMOTE_SDP
#define	ICF_TRACE_CMS_SDP_SEND	    ICF_TRACE_CMS_SDP_SEND
#define	ICF_TRACE_CMS_ADDR_SEND	    ICF_TRACE_CMS_ADDR_SEND
#define	ICF_TRACE_GCL_DATA_RECVD	    ICF_TRACE_GCL_DATA_RECVD
#define	ICF_TRACE_CMS_DATA_RECVD	    ICF_TRACE_CMS_DATA_RECVD
#define	ICF_TRACE_CMS_SDP_RECVD	    ICF_TRACE_CMS_SDP_RECVD
#define	ICF_TRACE_CMS_ADDR_RECVD	    ICF_TRACE_CMS_ADDR_RECVD
#define	ICF_TRACE_MERGE_DATA_SEND	ICF_TRACE_MERGE_DATA_SEND
#define	ICF_TRACE_CHR_START	    ICF_TRACE_CHR_START
#define	ICF_TRACE_NO_SDP_PRESENT	    ICF_TRACE_NO_SDP_PRESENT
#define	ICF_TRACE_NUMBER_OF_CODEC_DIFF	    ICF_TRACE_NUMBER_OF_CODEC_DIFF
#define	ICF_TRACE_CODEC_DIFF	    ICF_TRACE_CODEC_DIFF
#define	ICF_TRACE_CODEC_SAME	    ICF_TRACE_CODEC_SAME
#define	ICF_TRACE_TRANSPORT_ADDR_DIFF	    ICF_TRACE_TRANSPORT_ADDR_DIFF
#define	ICF_TRACE_PACKETIZATION_DIFF	    ICF_TRACE_PACKETIZATION_DIFF
#define	ICF_TRACE_SDP_SAME	    ICF_TRACE_SDP_SAME
#define	ICF_TRACE_TWC_START	    ICF_TRACE_TWC_START
#define	ICF_TRACE_TWC_RECVD	    ICF_TRACE_TWC_RECVD
#define	ICF_TRACE_MERGE_MEDIA_RESP	    ICF_TRACE_MERGE_MEDIA_RESP
#define	ICF_TRACE_BOTH_CALL_ACTIVE	    ICF_TRACE_BOTH_CALL_ACTIVE
#define	ICF_TRACE_TWC_STATE	    ICF_TRACE_TWC_STATE
#define	ICF_TRACE_TWC_EVENT	    ICF_TRACE_TWC_EVENT
#define	ICF_TWC_TRACE_MEDIA_NOT_COMMITTED	    ICF_TWC_TRACE_MEDIA_NOT_COMMITTED
#define	ICF_TWC_TRACE_CALL_LOCAL_HOLD	    ICF_TWC_TRACE_CALL_LOCAL_HOLD
#define	ICF_TWC_TRACE_END_OTHER_CALL	    ICF_TWC_TRACE_END_OTHER_CALL
#define	ICF_TWC_TRACE_TERMINATE_SERVICE	    ICF_TWC_TRACE_TERMINATE_SERVICE
#define	ICF_TWC_TRACE_MEDIA_ONGOING	    ICF_TWC_TRACE_MEDIA_ONGOING
#define	ICF_TWC_TRACE_MERGE_MEDIA_SENT	    ICF_TWC_TRACE_MERGE_MEDIA_SENT
#define	ICF_TWC_TRACE_FAILURE_CONF_RESP_SENT	    ICF_TWC_TRACE_FAILURE_CONF_RESP_SENT
#define	ICF_TWC_TRACE_BOTH_CALLS_ENDED	    ICF_TWC_TRACE_BOTH_CALLS_ENDED
#define	ICF_TWC_TRACE_CHR_SERVICE_ACTIVE_CHD	    ICF_TWC_TRACE_CHR_SERVICE_ACTIVE_CHD
#define	ICF_TWC_TRACE_CHR_SERVICE_ACTIVE_CRM	    ICF_TWC_TRACE_CHR_SERVICE_ACTIVE_CRM
#define	ICF_TWC_TRACE_INVALID_SERVICE_SCENARIO	    ICF_TWC_TRACE_INVALID_SERVICE_SCENARIO
#define	ICF_TWC_TRACE_BOTH_CALL_ENDED	    ICF_TWC_TRACE_BOTH_CALL_ENDED
#define	ICF_TRACE_CTU_RECVD	    ICF_TRACE_CTU_RECVD
#define	ICF_CTU_TRACE_CALL_RESUME_RESP_RECVD	    ICF_CTU_TRACE_CALL_RESUME_RESP_RECVD
#define	ICF_CTU_TRACE_CALL_HOLD_RESP_RECVD	    ICF_CTU_TRACE_CALL_HOLD_RESP_RECVD
#define	ICF_CTU_TRACE_REFER_REQ_SENT	    ICF_CTU_TRACE_REFER_REQ_SENT
#define	ICF_CTU_TRACE_REFER_REQ_WITH_REF_BY	    ICF_CTU_TRACE_REFER_REQ_WITH_REF_BY
#define	ICF_CTU_TRACE_PA_INITIATED_CALL_REL	    ICF_CTU_TRACE_PA_INITIATED_CALL_REL
#define	ICF_CTU_TRACE_CC_INITIATED_CALL_REL	    ICF_CTU_TRACE_CC_INITIATED_CALL_REL
#define	ICF_CTU_TRACE_INVALID_ADDRESS	    ICF_CTU_TRACE_INVALID_ADDRESS
#define	ICF_TRACE_TEL_URL	    ICF_TRACE_TEL_URL
#define	ICF_TRACE_INVALID_TEL_URL	    ICF_TRACE_INVALID_TEL_URL
#define	ICF_TRACE_E164_URL	    ICF_TRACE_E164_URL
#define	ICF_TRACE_INVALID_E164_URL	    ICF_TRACE_INVALID_E164_URL
#define	ICF_TRACE_SIP_URL	    ICF_TRACE_SIP_URL
#define	ICF_TRACE_INVALID_SIP_URL	    ICF_TRACE_INVALID_SIP_URL
#define	ICF_TRACE_CTU_STATE	    ICF_TRACE_CTU_STATE
#define	ICF_TRACE_CTU_EVENT	    ICF_TRACE_CTU_EVENT
#define	ICF_CFG_TRACE_SCALABLE_LINE_PRMS_REQ_RECD	    ICF_CFG_TRACE_SCALABLE_LINE_PRMS_REQ_RECD
#define	ICF_CFG_TRACE_SCALABLE_CALL_PRMS_REQ_RECD	    ICF_CFG_TRACE_SCALABLE_CALL_PRMS_REQ_RECD
#define	ICF_CFG_TRACE_TRNSPT_PRMS_REQ_RECD	    ICF_CFG_TRACE_TRNSPT_PRMS_REQ_RECD
#define	ICF_CFG_TRACE_PROXY_ADDR_REQ_RECD	    ICF_CFG_TRACE_PROXY_ADDR_REQ_RECD
#define	ICF_CFG_TRACE_PROXY_ADDR_LINE_RECD	    ICF_CFG_TRACE_PROXY_ADDR_LINE_RECD
#define	ICF_CFG_TRACE_PROXY_ADDR_RECD	    ICF_CFG_TRACE_PROXY_ADDR_RECD
#define	ICF_CFG_TRACE_SELF_TRNSPT_ADDR_RECD	    ICF_CFG_TRACE_SELF_TRNSPT_ADDR_RECD
#define	ICF_CFG_TRACE_CALL_PARAMS_RECD	    ICF_CFG_TRACE_CALL_PARAMS_RECD
#define	ICF_CFG_TRACE_CALL_DEFAULT_SETTING_N_QOS_RECD	    ICF_CFG_TRACE_CALL_DEFAULT_SETTING_N_QOS_RECD
#define	ICF_CFG_TRACE_CALL_TIMERS_RECD	    ICF_CFG_TRACE_CALL_TIMERS_RECD
#define	ICF_CFG_TRACE_REG_TIMERS_RECD	    ICF_CFG_TRACE_REG_TIMERS_RECD
#define	ICF_CFG_TRACE_SELF_ID_PRMS_RECD	    ICF_CFG_TRACE_SELF_ID_PRMS_REQ_RECD

#define	ICF_CFG_TRACE_SELF_ID_ADDR_PRMS_RECD	    ICF_CFG_TRACE_SELF_ID_ADDR_PRMS_RECD
#define	ICF_CFG_TRACE_SELF_ID_NAME_PRMS_RECD	    ICF_CFG_TRACE_SELF_ID_NAME_PRMS_RECD
#define	ICF_CFG_TRACE_SELF_ID_DEF_PRMS_RECD	    ICF_CFG_TRACE_SELF_ID_DEF_PRMS_RECD
#define	ICF_CFG_TRACE_SELF_ADDR_RECD	    ICF_CFG_TRACE_SELF_ADDR_RECD
#define	ICF_CFG_TRACE_SELF_NAME_RECD	    ICF_CFG_TRACE_SELF_NAME_RECD
#define	ICF_CFG_TRACE_SELF_DEF_RECD	    ICF_CFG_TRACE_SELF_DEF_RECD
#define	ICF_CFG_TRACE_REG_PRMS_REQ_RECD	    ICF_CFG_TRACE_REG_PRMS_REQ_RECD
#define	ICF_CFG_TRACE_REG_ADDR_PRMS_RECD	    ICF_CFG_TRACE_REG_ADDR_PRMS_RECD
#define	ICF_CFG_TRACE_REG_ADDR_RECD	    ICF_CFG_TRACE_REG_ADDR_RECD
#define	ICF_CFG_TRACE_REG_PRMS_RECD	    ICF_CFG_TRACE_REG_PRMS_RECD
#define	ICF_CFG_TRACE_SRVC_PRMS_REQ_RECD	    ICF_CFG_TRACE_SRVC_PRMS_REQ_RECD
#define	ICF_CFG_TRACE_SRVC_TIMERS_RECD	    ICF_CFG_TRACE_SRVC_TIMERS_RECD
#define	ICF_CFG_TRACE_CALL_FWD_TIMERS_RECD	    ICF_CFG_TRACE_CALL_FWD_TIMERS_RECD
#define	ICF_CFG_TRACE_SRVC_FLAGS_PRMS_RECD	    ICF_CFG_TRACE_SRVC_FLAGS_PRMS_RECD
#define	ICF_CFG_TRACE_SRVC_FLAGS_RECD	    ICF_CFG_TRACE_SRVC_FLAGS_RECD
#define	ICF_CFG_TRACE_CFU_ADDR_PRMS_RECD	    ICF_CFG_TRACE_CFU_ADDR_PRMS_RECD
#define	ICF_CFG_TRACE_CFU_ADDR_RECD	    ICF_CFG_TRACE_CFU_ADDR_RECD
#define	ICF_CFG_TRACE_CFB_ADDR_PRMS_RECD	    ICF_CFG_TRACE_CFB_ADDR_PRMS_RECD
#define	ICF_CFG_TRACE_CFB_ADDR_RECD	    ICF_CFG_TRACE_CFB_ADDR_RECD
#define	ICF_CFG_TRACE_CFD_ADDR_PRMS_RECD	    ICF_CFG_TRACE_CFD_ADDR_PRMS_RECD
#define	ICF_CFG_TRACE_CFD_ADDR_RECD	    ICF_CFG_TRACE_CFD_ADDR_RECD
#define	ICF_CFG_TRACE_RESP_SENT	    ICF_CFG_TRACE_RESP_SENT
#define	ICF_CFG_TRACE_SCALABLE_LINE_PRMS_SET	    ICF_CFG_TRACE_SCALABLE_LINE_PRMS_SET
#define	ICF_CFG_TRACE_SCALABLE_CALL_PRMS_SET	    ICF_CFG_TRACE_SCALABLE_CALL_PRMS_SET
#define	ICF_CFG_TRACE_PROXY_ADDR_LINE_SET	    ICF_CFG_TRACE_PROXY_ADDR_LINE_SET
#define	ICF_CFG_TRACE_PROXY_ADDRESS_SET	    ICF_CFG_TRACE_PROXY_ADDRESS_SET
#define	ICF_CFG_TRACE_SELF_TRNSPT_ADDR_SET	    ICF_CFG_TRACE_SELF_TRNSPT_ADDR_SET
#define	ICF_CFG_TRACE_SELF_TRNSPT_MODE_SET	    ICF_CFG_TRACE_SELF_TRNSPT_MODE_SET
#define	ICF_CFG_TRACE_CALL_DEFAULT_SETTING_N_QOS_SET	    ICF_CFG_TRACE_CALL_DEFAULT_SETTING_N_QOS_SET
#define	ICF_CFG_TRACE_CALL_TIMERS_SET	    ICF_CFG_TRACE_CALL_TIMERS_SET
#define	ICF_CFG_TRACE_REG_TIMERS_SET	    ICF_CFG_TRACE_REG_TIMERS_SET
#define	ICF_CFG_TRACE_MAX_NUM_OF_USERS_REACHED	    ICF_CFG_TRACE_MAX_NUM_OF_USERS_REACHED
#define	ICF_CFG_TRACE_SELF_ADDR_SET	    ICF_CFG_TRACE_SELF_ADDR_SET
#define	ICF_CFG_TRACE_SELF_NAME_SET	    ICF_CFG_TRACE_SELF_NAME_SET
#define	ICF_CFG_TRACE_SELF_DEFAULT_SETTINGS_SET	    ICF_CFG_TRACE_SELF_DEFAULT_SETTINGS_SET
#define	ICF_CFG_TRACE_LINE_BLK_DEALLOCATED	    ICF_CFG_TRACE_LINE_BLK_DEALLOCATED
#define	ICF_CFG_TRACE_REQ_ALREADY_RECD	    ICF_CFG_TRACE_REQ_ALREADY_RECD
#define	ICF_CFG_TRACE_REG_ADDR_SET	    ICF_CFG_TRACE_REG_ADDR_SET
#define	ICF_CFG_TRACE_REG_PRMS_SET	    ICF_CFG_TRACE_REG_PRMS_SET
#define	ICF_CFG_TRACE_SRVC_PRMS_SET	    ICF_CFG_TRACE_SRVC_PRMS_SET
#define	ICF_CFG_TRACE_SRVC_TIMERS_SET	    ICF_CFG_TRACE_SRVC_TIMERS_SET
#define	ICF_CFG_TRACE_CALL_FWD_TIMERS_SET	    ICF_CFG_TRACE_CALL_FWD_TIMERS_SET
#define	ICF_CFG_TRACE_SRVC_FLAGS_SET	    ICF_CFG_TRACE_SRVC_FLAGS_SET
#define	ICF_CFG_TRACE_CFU_ADDR_SET	    ICF_CFG_TRACE_CFU_ADDR_SET
#define	ICF_CFG_TRACE_CFB_ADDR_SET	    ICF_CFG_TRACE_CFB_ADDR_SET
#define	ICF_CFG_TRACE_CFD_ADDR_SET	    ICF_CFG_TRACE_CFD_ADDR_SET
#define	ICF_TRACE_DEREG_SUCCESS_RESP	    ICF_TRACE_DEREG_SUCCESS_RESP
#define	ICF_TRACE_REG_SUCCESS_RESP	    ICF_TRACE_REG_SUCCESS_RESP
#define	ICF_TRACE_DEREG_FAIL_RESP	    ICF_TRACE_DEREG_FAIL_RESP
#define	ICF_TRACE_REG_FAIL_RESP	    ICF_TRACE_REG_FAIL_RESP
#define	ICF_TRACE_DEREG_FAIL_NO_REATT_RESP	    ICF_TRACE_DEREG_FAIL_NO_REATT_RESP
#define	ICF_TRACE_REG_FAIL_NO_REATT_RESP	    ICF_TRACE_REG_FAIL_NO_REATT_RESP
#define	ICF_TRACE_AUTHENTICATION_REQ	    ICF_TRACE_AUTHENTICATION_REQ
#define	ICF_TRACE_DURATION_SHORT	    ICF_TRACE_DURATION_SHORT
#define	ICF_SM_TRACE_START	    ICF_SM_TRACE_START
#define	ICF_SM_TRACE_TRACE_LVL_REQ_RECD	    ICF_SM_TRACE_TRACE_LVL_REQ_RECD
#define	ICF_SM_TRACE_ERROR_LVL_REQ_RECD	    ICF_SM_TRACE_ERROR_LVL_REQ_RECD
#define	ICF_SM_TRACE_SET_STATS_REQ_RECD	    ICF_SM_TRACE_SET_STATS_REQ_RECD
#define	ICF_SM_TRACE_GET_STATS_REQ_RECD	    ICF_SM_TRACE_GET_STATS_REQ_RECD
#define	ICF_SM_TRACE_GET_STATS_RESP_SENT	    ICF_SM_TRACE_GET_STATS_RESP_SENT
#define	ICF_SM_TRACE_CHK_MODULE_REQ_RECD	    ICF_SM_TRACE_CHK_MODULE_REQ_RECD
#define	ICF_SM_TRACE_CHK_MODULE_RESP_SENT	    ICF_SM_TRACE_CHK_MODULE_RESP_SENT
#define	ICF_SM_TRACE_CALL_LOG_REQ_RECD	    ICF_SM_TRACE_CALL_LOG_REQ_RECD
#define	ICF_SM_TRACE_CALL_LOG_RESP_SENT	    ICF_SM_TRACE_CALL_LOG_RESP_SENT
#define	ICF_SM_TRACE_VALIDATE_PARAM	    ICF_SM_TRACE_VALIDATE_PARAM
#define	ICF_SM_TRACE_NUM_CALLS_RECORD	    ICF_SM_TRACE_NUM_CALLS_RECORD
#define	ICF_SM_TRACE_DIALED_CALL_LOG_REQ	    ICF_SM_TRACE_DIALED_CALL_LOG_REQ
#define	ICF_SM_TRACE_DIALED_CALL_LOG_RESP	    ICF_SM_TRACE_DIALED_CALL_LOG_RESP
#define	ICF_SM_TRACE_MISSED_CALL_LOG_REQ	    ICF_SM_TRACE_MISSED_CALL_LOG_REQ
#define	ICF_SM_TRACE_MISSED_CALL_LOG_RESP	    ICF_SM_TRACE_MISSED_CALL_LOG_RESP
#define	ICF_SM_TRACE_RECD_CALL_LOG_REQ	    ICF_SM_TRACE_RECD_CALL_LOG_REQ
#define	ICF_SM_TRACE_RECD_CALL_LOG_RESP	    ICF_SM_TRACE_RECD_CALL_LOG_RESP
#define	ICF_TRACE_INVALID_MSG_ID_RECD	    ICF_TRACE_INVALID_MSG_ID_RECD
#define	ICF_TRACE_INVALID_API_ID_RECD	    ICF_TRACE_INVALID_API_ID_RECD
#define	ICF_TRACE_SEND_RESP_FAILURE	    ICF_TRACE_SEND_RESP_FAILURE
#define	ICF_TRACE_CTA_START	    ICF_TRACE_CTA_START
#define	ICF_TRACE_CTA_RECVD	    ICF_TRACE_CTA_RECVD
#define	ICF_CTA_TRACE_CALL_RESUME_RESP_RECVD	    ICF_CTA_TRACE_CALL_RESUME_RESP_RECVD
#define	ICF_CTA_TRACE_CALL_HOLD_RESP_RECVD	    ICF_CTA_TRACE_CALL_HOLD_RESP_RECVD
#define	ICF_CTA_TRACE_REFER_REQ_SENT	    ICF_CTA_TRACE_REFER_REQ_SENT
#define	ICF_CTA_TRACE_PA_INITIATED_CALL_REL	    ICF_CTA_TRACE_PA_INITIATED_CALL_REL
#define	ICF_CTA_TRACE_CC_INITIATED_CALL_REL	    ICF_CTA_TRACE_CC_INITIATED_CALL_REL
#define	ICF_TRACE_CTA_STATE	    ICF_TRACE_CTA_STATE
#define	ICF_TRACE_CTA_EVENT	    ICF_TRACE_CTA_EVENT
#define	ICF_CTA_TRACE_NOTIFY_RESP_SENT	    ICF_CTA_TRACE_NOTIFY_RESP_SENT
#define	ICF_TRACE_RNW_START	    ICF_TRACE_RNW_START
#define	ICF_TRACE_RNW_RECVD	    ICF_TRACE_RNW_RECVD
#define	ICF_TRACE_RNW_WITH_REPLACES	    ICF_TRACE_RNW_WITH_REPLACES
#define	ICF_TRACE_RNW_NEW_CALL_ID	    ICF_TRACE_RNW_NEW_CALL_ID
#define	ICF_RNW_TRACE_REFER_RESP_SENT	    ICF_RNW_TRACE_REFER_RESP_SENT
#define	ICF_RNW_TRACE_NOTIFY_SENT	    ICF_RNW_TRACE_NOTIFY_SENT
#define	ICF_RNW_TRACE_CC_INITIATED_CALL_REL	    ICF_RNW_TRACE_CC_INITIATED_CALL_REL
#define	ICF_TRACE_MERGE_IND_SENT	    ICF_TRACE_MERGE_IND_SENT
#define	ICF_TRACE_MERGE_MEDIA_SENT	    ICF_TRACE_MERGE_MEDIA_SENT
#define	ICF_TRACE_REFER_IND_SENT	    ICF_TRACE_REFER_IND_SENT
#define	ICF_RNW_TRACE_NEXT_STATE	    ICF_RNW_TRACE_NEXT_STATE
#define	ICF_TRACE_RNW_STATE	    ICF_TRACE_RNW_STATE
#define	ICF_TRACE_RNW_EVENT	    ICF_TRACE_RNW_EVENT
#define	ICF_TRACE_CFW_START	    ICF_TRACE_CFW_START
#define	ICF_CFW_TRACE_VALIDITY	    ICF_CFW_TRACE_VALIDITY
#define	ICF_CFW_TRACE_MSG_SEND	    ICF_CFW_TRACE_MSG_SEND
#define	ICF_CFW_TRACE_MSG_SEND_FAILURE	    ICF_CFW_TRACE_MSG_SEND_FAILURE
#define	ICF_CFW_TRACE_FAIL_TO_GET_CFG_DATA	    ICF_CFW_TRACE_FAIL_TO_GET_CFG_DATA
#define	ICF_CFW_TRACE_LINE_ID	    ICF_CFW_TRACE_LINE_ID
#define	ICF_CFW_TRACE_FAIL_TO_GET_LINE_DATA	    ICF_CFW_TRACE_FAIL_TO_GET_LINE_DATA
#define	ICF_CFW_TRACE_CFW_TYPE	    ICF_CFW_TRACE_CFW_TYPE
#define	ICF_CFW_TRACE_CALLING_CFW_ADDR_MATCH	    ICF_CFW_TRACE_CALLING_CFW_ADDR_MATCH
#define	ICF_CFW_TRACE_INVALID_HOPS	    ICF_CFW_TRACE_INVALID_HOPS
#define	ICF_CFW_TRACE_CFW_DIV_ADDR_MATCH	    ICF_CFW_TRACE_CFW_DIV_ADDR_MATCH
#define	ICF_CFW_TRACE_SELF_CFW_ADDR_MATCH	    ICF_CFW_TRACE_SELF_CFW_ADDR_MATCH
#define	ICF_CFW_TRACE_DIV_INFO_PRESENT	    ICF_CFW_TRACE_DIV_INFO_PRESENT
#define	ICF_CFW_TRACE_DIV_INFO_NOT_PRESENT	    ICF_CFW_TRACE_DIV_INFO_NOT_PRESENT
#define	ICF_CFW_TRACE_DATA_SEND	    ICF_CFW_TRACE_DATA_SEND
#define	ICF_CFW_TRACE_REL_TYPE_N_CAUSE	    ICF_CFW_TRACE_REL_TYPE_N_CAUSE
#define	ICF_CFW_TRACE_STATUS	    ICF_CFW_TRACE_STATUS
#define	ICF_CFW_TRACE_INVALID_MSG_ID	    ICF_CFW_TRACE_INVALID_MSG_ID
#define	ICF_CFW_TRACE_INVALID_CFW_TYPE	    ICF_CFW_TRACE_INVALID_CFW_TYPE
#define	ICF_TRACE_INIT_COMPLETE_RECD	    ICF_TRACE_INIT_COMPLETE_RECD

/*ICF_CRM_START*/
#define  ICF_CFG_TRACE_NETWORK_ACTIVATE_RECD    ICF_CFG_TRACE_NETWORK_ACTIVATE_RECD
#define  ICF_CFG_TRACE_NETWORK_DEACTIVATE_RECD  ICF_CFG_TRACE_NETWORK_DEACTIVATE_RECD
#define  ICF_CFG_TRACE_APP_ADD_RECD             ICF_CFG_TRACE_APP_ADD_RECD
#define  ICF_CFG_TRACE_APP_REMOVE_RECD          ICF_CFG_TRACE_APP_REMOVE_RECD
/*ICF_CRM_END*/
/*ICF_CONF_STATUS_API_START */
#define  ICF_CFG_TRACE_GET_SYSTEM_SETTINGS_RECD ICF_CFG_TRACE_GET_SYSTEM_SETTINGS_RECD
#define  ICF_CFG_TRACE_GET_LINE_SETTINGS_RECD   ICF_CFG_TRACE_GET_LINE_SETTINGS_RECD    
/* ICF_CONF_STATUS_API_END  */
#define	ICF_TRACE_ERROR_BASE	    ICF_TRACE_ERROR_BASE
#define	ICF_MAX_NUM_OF_TRACE_IDS	    ICF_MAX_NUM_OF_TRACE_IDS
                       
/***************************************************************/
#define ICF_CFG_TRACE_CALL_PRMS_SET          ICF_CFG_TRACE_CALL_PRMS_SET

#define ICF_CFG_TRACE_SELF_ADDR_PRMS_SET     ICF_CFG_TRACE_SELF_ADDR_PRMS_SET

#define ICF_CFG_TRACE_SELF_NAME_N_DEF_SET_RECD ICF_CFG_TRACE_SELF_NAME_N_DEF_SET_RECD

#define ICF_CFG_TRACE_SELF_ID_PRMS_REQ_RECD ICF_CFG_TRACE_SELF_ID_PRMS_REQ_RECD

/*****************************************************************/
#ifdef ICF_SERVICE_ENABLE

#define ICF_CFG_TRACE_SRVC_SUBSCRIBE_PRMS_SET	ICF_CFG_TRACE_SRVC_SUBSCRIBE_PRMS_SET
#define	ICF_CFG_TRACE_SRVC_SUBS_FLAG_RECD		ICF_CFG_TRACE_SRVC_SUBS_FLAG_RECD
#define ICF_CFG_TRACE_SRVC_ACT_FLAG_RECD			ICF_CFG_TRACE_SRVC_ACT_FLAG_RECD
#define ICF_CFG_TRACE_SRVC_SUBSCRIBE_PRMS_RECD	ICF_CFG_TRACE_SRVC_SUBSCRIBE_PRMS_RECD
#endif

#define ICF_TRACE_MED_CAP_REQ                       ICF_TRACE_MED_CAP_REQ
#define ICF_TRACE_MED_CAP_RESP                      ICF_TRACE_MED_CAP_RESP

#define ICF_TRACE_ENTERED_SSA_PROCESS_MESG          ICF_TRACE_ENTERED_SSA_PROCESS_MESG
#define ICF_TRACE_APP_POINTER                       ICF_TRACE_APP_POINTER
#define ICF_TRACE_SSA_BITMASK                       ICF_TRACE_SSA_BITMASK
#define ICF_TRACE_TCP_CONN_DB_INDEX                 ICF_TRACE_TCP_CONN_DB_INDEX
#define ICF_TRACE_TCP_EVENT                         ICF_TRACE_TCP_EVENT
#define ICF_TRACE_STRAY_MSG_RECVD                   ICF_TRACE_STRAY_MSG_RECVD
#define ICF_TRACE_DEST_MODULE_ID                    ICF_TRACE_DEST_MODULE_ID
#define ICF_TRACE_SIP_METHOD                        ICF_TRACE_SIP_METHOD
#define ICF_TRACE_CALL_LEG_MATCHED                  ICF_TRACE_CALL_LEG_MATCHED
#define ICF_TRACE_UPDATE_CALL_DET_STATUS            ICF_TRACE_UPDATE_CALL_DET_STATUS
#define ICF_TRACE_SSA_PDB_BITMASK                   ICF_TRACE_SSA_PDB_BITMASK
#define ICF_TRACE_SSA_CTX_FAILURE_BITMASK           ICF_TRACE_SSA_CTX_FAILURE_BITMASK
#define ICF_TRACE_SENT_RESP_CODE                    ICF_TRACE_SENT_RESP_CODE
#define ICF_TRACE_TRANSPORT_MODE                    ICF_TRACE_TRANSPORT_MODE
#define ICF_TRACE_TRANSPORT_SCHEME                  ICF_TRACE_TRANSPORT_SCHEME
#define ICF_TRACE_NUMBER_OF_DIV_HDRS                ICF_TRACE_NUMBER_OF_DIV_HDRS
#define ICF_TRACE_PRIV_HDR_PRESENT                  ICF_TRACE_PRIV_HDR_PRESENT
#define ICF_TRACE_REF_BY_HDR_PRESENT                ICF_TRACE_REF_BY_HDR_PRESENT
#define ICF_TRACE_REPLACES_HDR_PRESENT              ICF_TRACE_REPLACES_HDR_PRESENT
#define ICF_TRACE_TCP_STATE                         ICF_TRACE_TCP_STATE
#define ICF_TRACE_TRANS_MODE_REVERT_TO_UDP          ICF_TRACE_TRANS_MODE_REVERT_TO_UDP
#define ICF_TRACE_CONNECT_SENT_WO_SDP               ICF_TRACE_CONNECT_SENT_WO_SDP
#define ICF_TRACE_OTG_RPR_PRESENT                   ICF_TRACE_OTG_RPR_PRESENT
#define ICF_TRACE_SIP_METHOD_SENT                   ICF_TRACE_SIP_METHOD_SENT
#define ICF_TRACE_SIP_METHOD_RCVD                   ICF_TRACE_SIP_METHOD_RCVD
#define ICF_TRACE_PRACK_SENT_W_SDP                  ICF_TRACE_PRACK_SENT_W_SDP
#define ICF_TRACE_MED_CHNG_RESP                     ICF_TRACE_MED_CHNG_RESP
#define ICF_TRACE_CALL_HOLD_TYPE                    ICF_TRACE_CALL_HOLD_TYPE
#define ICF_TRACE_NOTIFY_EVENT                      ICF_TRACE_NOTIFY_EVENT
#define ICF_TRACE_REG_REQ                           ICF_TRACE_REG_REQ
#define ICF_TRACE_TIMER_START                       ICF_TRACE_TIMER_START
#define ICF_TRACE_TIMER_STOP                        ICF_TRACE_TIMER_STOP
#define ICF_TRACE_TIMER_EXPIRY                      ICF_TRACE_TIMER_EXPIRY
#define ICF_TRACE_SOCKET_CONNECTED                  ICF_TRACE_SOCKET_CONNECTED
#define ICF_TRACE_FREE_APP_DATA_CALLED              ICF_TRACE_FREE_APP_DATA_CALLED
#define ICF_TRACE_IND_TXN_TIMED_OUT                 ICF_TRACE_IND_TXN_TIMED_OUT
#define ICF_TRACE_TEL_URL_TO_IP_ADDR                ICF_TRACE_TEL_URL_TO_IP_ADDR
#define ICF_TRACE_REPLACE_NW_CALL_ID                ICF_TRACE_REPLACE_NW_CALL_ID
#define ICF_TRACE_VALIDATION_OF_REQ_URI_FAILURE     ICF_TRACE_VALIDATION_OF_REQ_URI_FAILURE
#define ICF_TRACE_MEDIA_CHANGE_RCVD_W_SDP           ICF_TRACE_MEDIA_CHANGE_RCVD_W_SDP
#define ICF_TRACE_OPTIONS_RCVD_OUT_OF_DIALOG        ICF_TRACE_OPTIONS_RCVD_OUT_OF_DIALOG
#define ICF_TRACE_OPTIONS_USER_NOT_FOUND            ICF_TRACE_OPTIONS_USER_NOT_FOUND
#define ICF_TRACE_OPTIONS_USER_BUSY                 ICF_TRACE_OPTIONS_USER_BUSY
#define ICF_TRACE_SUBSCRIBE_EVENT_PACKAGE           ICF_TRACE_SUBSCRIBE_EVENT_PACKAGE
#define ICF_TRACE_SUBSCRIBE_RESP                    ICF_TRACE_SUBSCRIBE_RESP
#define ICF_TRACE_NOTIFY_RCVD                       ICF_TRACE_NOTIFY_RCVD
#define ICF_TRACE_INFO_RCVD_W_PAYLOAD               ICF_TRACE_INFO_RCVD_W_PAYLOAD
#define ICF_TRACE_SUPPORTED_100_REL_PRESENT         ICF_TRACE_SUPPORTED_100_REL_PRESENT
#define ICF_TRACE_NOTIFY_RCVD_N_CTXT_DELINKED       ICF_TRACE_NOTIFY_RCVD_N_CTXT_DELINKED
#define ICF_TRACE_PHONE_CTXT_RECVD                  ICF_TRACE_PHONE_CTXT_RECVD
#define ICF_TRACE_MSG_TYPE_N_STATE_IN_OVLAP_TXN     ICF_TRACE_MSG_TYPE_N_STATE_IN_OVLAP_TXN
#define ICF_TRACE_EXIT_PROCESS_MESG                 ICF_TRACE_EXIT_PROCESS_MESG

#define ICF_SIP_STACK_BRIEF_TRACE                   ICF_SIP_STACK_BRIEF_TRACE
#define ICF_SIP_STACK_DETAILED_TRACE                ICF_SIP_STACK_DETAILED_TRACE
#define ICF_SIP_STACK_DEBUG_TRACE                   ICF_SIP_STACK_DEBUG_TRACE

#define ICF_CFG_TRACE_VMS_PRMS_RECD                 ICF_CFG_TRACE_VMS_PRMS_RECD
#define ICF_CFG_TRACE_VMS_ADDR_PRMS_RECD            ICF_CFG_TRACE_VMS_ADDR_PRMS_RECD
#define ICF_CFG_TRACE_VMS_OTHER_PRMS_RECD           ICF_CFG_TRACE_VMS_OTHER_PRMS_RECD

#define ICF_CFG_TRACE_VMS_GRP_ADDR_PRMS_SET         ICF_CFG_TRACE_VMS_GRP_ADDR_PRMS_SET
#define ICF_CFG_TRACE_VMS_GRP_PRMS_SET              ICF_CFG_TRACE_VMS_GRP_PRMS_SET
#define ICF_CFG_TRACE_VMS_LINE_ADDR_PRMS_SET        ICF_CFG_TRACE_VMS_LINE_ADDR_PRMS_SET
#define ICF_CFG_TRACE_VMS_LINE_PRMS_SET             ICF_CFG_TRACE_VMS_LINE_PRMS_SET
#define ICF_CFG_TRACE_SRVC_SUBSCRIBE_PRMS_SET       ICF_CFG_TRACE_SRVC_SUBSCRIBE_PRMS_SET

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* End of __ICF_ICF_MAP_TRACE_ID_H__ */
