/******************************************************************************
*                                    
* FILE NAME    : nat_error_id.h                 
*                                    
* DESCRIPTION  : Contains the error IDs
*                
*                                    
* Revision History :                            
*
*  DATE            NAME              REFERENCE       REASON        
* ------         ------------       ---------     ----------
* 12-Jul-2006	Anuradha Gupta			LLD	     Initial Version
* 24-Nov-2006	Anuradha Gupta			Code	New error IDs added
*
* Copyright 2006, Aricent                       
*                                    
*******************************************************************************/

#ifndef __NAT_ERROR_ID_H_
#define __NAT_ERROR_ID_H_


#ifdef __cplusplus

extern "C"
{
#endif

#define NAT_ERR_NONE				0
#define NAT_ERR_UNDEFINED			0

#define NAT_ERR_COMMON_START			1

#define NAT_ERR_MEM_ALLOC_FAILURE		NAT_ERR_COMMON_START
#define NAT_ERR_MEM_FREE_FAILURE		NAT_ERR_COMMON_START + 1
#define NAT_ERR_TMR_START_FAILURE		NAT_ERR_COMMON_START + 2
#define NAT_ERR_TMR_STOP_FAILURE		NAT_ERR_COMMON_START + 3
#define NAT_ERR_INVALID_API_ID			NAT_ERR_COMMON_START + 4
#define NAT_ERR_UDP_SEND			NAT_ERR_COMMON_START + 5
#define NAT_ERR_TCP_SEND			NAT_ERR_COMMON_START + 6
#define NAT_ERR_SOCKET_CREATE			NAT_ERR_COMMON_START + 7
#define NAT_ERR_SOCKET_BIND			NAT_ERR_COMMON_START + 8
#define NAT_ERR_UDP_RECV			NAT_ERR_COMMON_START + 9
#define NAT_ERR_TCP_RECV			NAT_ERR_COMMON_START + 10
#define NAT_ERR_ENCODE_FAILED			NAT_ERR_COMMON_START + 11
#define NAT_ERR_DECODE_FAILED			NAT_ERR_COMMON_START + 12
#define NAT_ERR_OPEN_SECURE_CONN_FAILED		NAT_ERR_COMMON_START + 13
#define NAT_ERR_INVALID_SOURCE_ID		NAT_ERR_COMMON_START + 14
#define NAT_ERR_INVALID_DESTINATION_ID		NAT_ERR_COMMON_START + 15
#define NAT_ERR_MAX_CONTEXT_EXCEEDED		NAT_ERR_COMMON_START + 16
#define NAT_ERR_SHARED_SECRET_PENDING       	NAT_ERR_COMMON_START + 17
#define NAT_ERR_SHARED_SECRET_ONGOING		NAT_ERR_COMMON_START + 18	
#define NAT_ERR_BINDING_LIFETIME_PENDING	NAT_ERR_COMMON_START + 19
#define NAT_ERR_BINDING_LIFETIME_ONGOING	NAT_ERR_COMMON_START + 20
#define NAT_ERR_TYPE_DISCOVERY_PENDING		NAT_ERR_COMMON_START + 21
#define NAT_ERR_TYPE_DISCOVERY_ONGOING		NAT_ERR_COMMON_START + 22
#define NAT_ERR_PROTOCOL_NOT_SUPPORTED		NAT_ERR_COMMON_START + 23
#define NAT_ERR_UDP_BLOCKED                 	NAT_ERR_COMMON_START + 24
#define NAT_ERR_SHSEC_MISMATCH              	NAT_ERR_COMMON_START + 25
#define NAT_ERR_MEM_INIT			NAT_ERR_COMMON_START + 26
#define NAT_ERR_MEM_DEINIT			NAT_ERR_COMMON_START + 27
#define NAT_ERR_TMR_INIT			NAT_ERR_COMMON_START + 28
#define NAT_ERR_TMR_DEINIT			NAT_ERR_COMMON_START + 29
#define NAT_ERR_SET_SOCKET          		NAT_ERR_COMMON_START + 30
#define NAT_ERR_BAD_MSG_RECVD			NAT_ERR_COMMON_START + 31
#define NAT_ERR_CONNECT_RESP_PENDING		NAT_ERR_COMMON_START + 32
#define NAT_ERR_IP_MISMATCH         NAT_ERR_COMMON_START + 33
#define NAT_ERR_PORT_MISMATCH         NAT_ERR_COMMON_START + 34
#define NAT_ERR_MSG_INTEGRITY_FAIL      NAT_ERR_COMMON_START + 35
#define NAT_ERR_COMMON_END			NAT_ERR_COMMON_START + 99 

#define NAT_ERR_STUN_START			NAT_ERR_COMMON_END+ 1	/*101*/

#define NAT_ERR_STUN_INVALID_VALUE		NAT_ERR_STUN_START
#define NAT_ERR_STUN_INVALID_PROC		NAT_ERR_STUN_START + 1
#define NAT_ERR_STUN_NO_BINDING_RESPONSE	NAT_ERR_STUN_START + 2
#define NAT_ERR_STUN_BAD_REQUEST		NAT_ERR_STUN_START + 3
#define NAT_ERR_STUN_UNAUTH_RETRY		NAT_ERR_STUN_START + 4
#define NAT_ERR_STUN_UNKNOWN_ATTR_RETRY		NAT_ERR_STUN_START + 5
#define NAT_ERR_STUN_STALE_CREDIT_RETRY		NAT_ERR_STUN_START + 6
#define NAT_ERR_STUN_INTEG_CHECK_FAIL_RETRY	NAT_ERR_STUN_START + 7
#define NAT_ERR_STUN_MISSING_USRNAME_RETRY	NAT_ERR_STUN_START + 8
#define NAT_ERR_STUN_SERVER_ERROR_RETRY		NAT_ERR_STUN_START + 9
#define NAT_ERR_STUN_GLOBAL_FAILURE_NO_RETRY	NAT_ERR_STUN_START + 10
#define NAT_ERR_STUN_FAILURE_POSSIBLE_ATTACK	NAT_ERR_STUN_START + 11
#define NAT_ERR_STUN_NO_CONTEXT_AVAILABLE	NAT_ERR_STUN_START + 12
#define NAT_ERR_STUN_DECODE_MSG_INTEGRITY_FAIL NAT_ERR_STUN_START + 13
#define NAT_ERR_STUN_INIT_NOT_COMPLETE          NAT_ERR_STUN_START + 14
#define NAT_ERR_STUN_INIT_ALREADY_DONE		NAT_ERR_STUN_START + 15
#define NAT_ERR_STUN_DECODE_MSG_VALIDATION_FAIL NAT_ERR_STUN_START + 16
#define NAT_ERR_STUN_END			NAT_ERR_STUN_START + 50

#define NAT_ERR_MISC_START			NAT_ERR_STUN_END+ 1	/*151*/


#define NAT_ERR_MISC_END			NAT_ERR_MISC_START + 49

#ifdef __cplusplus

}
#endif

#endif /*__NAT_ERROR_ID_H_ */

