
/* Ensure Names are not mangled by C++ compilers */
#ifdef __cplusplus
extern "C" {
#endif 

/**************************************************************************
** FUNCTION:
**  This file contains the prototypes of the Timer APIs
**
***************************************************************************
**
** FILENAME:
**  microsip_timer.h
**
** DESCRIPTION
**
**
**  DATE           NAME                       REFERENCE
** 23-02-2002	mahesh							CoreStack
**
** COPYRIGHT , Aricent, 2006
***************************************************************************/


#ifndef _SIPTIMER_H_
#define _SIPTIMER_H_
#include "microsip_common.h"
#include "microsip_struct.h"
#define TIMER_NONE       4

typedef SipBool (*sip_timeoutFuncPtr)(SipTimerKey *key, SIP_Pvoid buf);

/*****************************************************************
** Function: fast_startTimer
** Description: Timer management callback to be implemented by the
**		application. 
** Parameters:
**		duration(IN): The duration in milliseconds after which the 
**			application must call timoutfunc with buffer and key
**			as parameters.
**		restart(IN): Currently not used. 0 to be passed.
**		timeoutfunc(IN): A function supplied by the stack. The
**			application must invoke this function when the timer
**			expires. The application must pass the buffer and key
**			passed to this function.
**		buffer(IN): The first parameter to be supplied to the timeout
**			function supplied by the stack.
**		key(IN): The second paramter to be supplied to the timeout
**			function provided by the stack.
**		err(OUT): Error code may be returned in this if the call fails.
**
*******************************************************************/
extern SipBool fast_startTimer _ARGS_((SIP_U32bit duration, \
	SIP_S8bit restart, sip_timeoutFuncPtr timoutfunc, \
		SIP_Pvoid buffer, SipTimerKey *key, SipError *err));

/*****************************************************************
** Function: fast_stoptTimer
** Description: Timer management callback to be implemented by the
**		application.
** Parameters:
**		inkey(IN): The key to be used to search the list of timers
**			maintained by the application. The application must use
**			the sip_compareTimerKeys function to search for a matching
**			entry. Please refer to the note in the sip_compareTimerKey
**			description.
**		outkey(OUT): Any matching key must be returned in outkey. The
**			stack releases memory used by outkey.
**		buffer(OUT): The buffer associated with the matching entry is
**			to be retured in this to the stack for releasing memory.
**		err(OUT): The error code is set into this in case of failure.
**
*******************************************************************/
extern SipBool fast_stopTimer _ARGS_((SipTimerKey *inkey, \
	SipTimerKey **outkey, SIP_Pvoid *buffer,  SipError *err));

/*****************************************************************
** Function: sip_compareTimerKeys
** Description: Function used for comparing Timer keys generated by
**		the stack with the keys stored by the application.
**		Note: the first two parameters are not interchangeable.
**		Comparing every key in the applications timer list using this
**		function may be a costly operation. The user may eliminate keys
**		by comparing the pCallid fields of the timer keys before invoking 
**		this function. Other fields in the timer keys may differ for 
**		matching keys and should not be used for elimination/hashing.
** Parameters:
**		paramkey(IN): This should be set to the key supplied by the 
**			stack in fast_stopTimer.
**		storedkey(IN): This should be set to the key in the list that 
**			was supplied by fast_startTimer. 
**		err(OUT):
** Return Value:
**		SipSuccess: The timer keys matched.
**		SipFail: The timer keys do not match.
**
*******************************************************************/
extern SipBool sip_compareTimerKeys _ARGS_((SipTimerKey *paramkey, \
	SipTimerKey *storedkey, SipError *err));

/*****************************************************************
** Function: sip_freeEventContext
** Description: Callback to be implemted by the application. This
**		callback is invoked by the stack when it needs to free
**		the context structure since the stack is not aware of the 
**		contents set by the application. The application must free
**		the pData element and the SipEventContext structure.
** Parameters:
**		pContext(IN): The structure to be released by the application.
**
*******************************************************************/
extern void sip_freeEventContext(SipEventContext *pContext);

/*****************************************************************
** The following functions are internal functions.
*******************************************************************/
/*******************************************************************************
** FUNCTION: sip_stopTimer
** DESCRIPTION: This function stops the timer.
** 
** PARAMETERS:
**      	      	msg(IN)		:The SipMessage
**			       pContext(IN)	:The event Context structure
**				  	err(IN)		:The error Value
** Return Value:
**				  SipBool	
*******************************************************************************/
extern SipBool sip_stopTimer _ARGS_((SipMessage *msg, SipEventContext *pContext ,SipError *err));
/*******************************************************************************
** FUNCTION: sip_updateTimer
** DESCRIPTION: This function is invoked by the stack to change retrans
** count of a message. 
** 
** PARAMETERS:
**      	      	msg(IN)		:The SipMessage
**			       infoflag(IN)	:The infoflag.This is to indicate, 
**								 the receipt of provisional response.
**			       pContext(IN)	:The event Context structure
**				  	err(IN)		:The error Value
** Return Value:
**				  SipBool	
*******************************************************************************/
extern SipBool sip_updateTimer _ARGS_((SipMessage *msg, \
	SipBool infoflag,SipEventContext *pContext, SipError *err));
/*******************************************************************************
** FUNCTION: sip_processTimeOut
** DESCRIPTION: This function is invoked by the timer manager
** when a Time out occurs. It is passed the TimerKey and the TimerBuffer
** of the timeout Context
** 
** PARAMETERS:
**      	      	pKey(IN)		:The SipMessage
**			       pBuffer(IN)	:The infoflag.This is to indicate, 
** Return Value:
**				  SipBool	
*******************************************************************************/
SipBool sip_processTimeOut(SipTimerKey *pKey, SIP_Pvoid pBuffer);
	

/*******************************************************************************
** FUNCTION: sip_getCharString
** DESCRIPTION: Converts escaped values in  astring to unescaped one
** 
** PARAMETERS:
**      	      	inputstr(IN)			:The input string
**				 	outstr(OUT)				:The outputstring 
**				  	err(IN)					:The error Value
** Return Value:
**				  SipBool	
*******************************************************************************/
extern SipBool sip_getCharString _ARGS_((SIP_S8bit *inputstr, \
	SIP_S8bit **outstr, SipError *err));
/*******************************************************************************
** FUNCTION: sip_isEqualPort
** DESCRIPTION: Compares two ports for their equality.
** 
** PARAMETERS:
**      	      	port1(IN)				:The port1
**      	      	port2(IN)				:The port2
** Return Value:
**				  SipBool	
*******************************************************************************/
extern SipBool sip_isEqualPort _ARGS_((SIP_U16bit *port1,\
	SIP_U16bit *port2));
/*******************************************************************************
** FUNCTION: sip_isEqualSipUrl
** DESCRIPTION: Compares two SipUrls  for their equality.
** 
** PARAMETERS:
**      	      	inputstr(IN)			:The input string
**				 	outstr(OUT)				:The outputstring 
**				  	err(IN)					:The error Value
** Return Value:
**				  SipBool	
*******************************************************************************/
extern SipBool sip_isEqualSipUrl _ARGS_((SipUrl *url1, \
	SipUrl *url2, SipError *err));

/*******************************************************************************
** FUNCTION: sip_isEqualReqUri
** DESCRIPTION: Compares two ReqUris  for their equality.
** 
** PARAMETERS:
**      	      	uri1(IN)				:First uri
**				 	uri2(OUT)				:Second URi 
**				  	err(IN)					:The error Value
** Return Value:
**				  SipBool	
*******************************************************************************/
extern SipBool sip_isEqualReqUri _ARGS_((SIP_S8bit *uri1,\
	SIP_S8bit *uri2, SipError *err));
/*******************************************************************************
** FUNCTION: sip_getBranchFromViaHdr
** DESCRIPTION: gets Branch parameter from ViaHeader.
** 
** PARAMETERS:
**      	      	pViaHeader(IN)				:Via header from which 
**												 branch has to be retrieved
**				 	ppBranch(Out)				:Branch parameter retrieved
**				  	pErr(IN)					:The error Value
** Return Value:
**				  SipBool	
*******************************************************************************/
extern SipBool sip_getBranchFromViaHdr _ARGS_((SipViaHeader *pViaHeader, \
	SIP_S8bit **ppBranch, SipError *pErr));
/*******************************************************************************
** FUNCTION: sip_compareToHeaders
** DESCRIPTION: Compares two To headers  for their equality.
** 
** PARAMETERS:
**      	      	hdr1(IN)				:First to header
**				 	hdr2(IN)				:Second toheader
**				  	err(IN)					:The error Value
** Return Value:
**				  SipBool	
*******************************************************************************/
extern SipBool sip_compareToHeaders _ARGS_((SipToHeader *hdr1,SipToHeader	*hdr2,SipError*err));
/*******************************************************************************
** FUNCTION: sip_compareFromHeaders
** DESCRIPTION: Compares two From headers  for their equality.
** 
** PARAMETERS:
**      	      	hdr1(IN)				:First to header
**				 	hdr2(IN)				:Second toheader
**				  	err(IN)					:The error Value
** Return Value:
**				  SipBool	
*******************************************************************************/
extern SipBool sip_compareFromHeaders _ARGS_(( SipFromHeader *hdr1,SipFromHeader	*hdr2,SipError	*err ));
#ifndef SIP_TXN_LAYER
/*******************************************************************************
** FUNCTION: sip_indicateTimeOut
** DESCRIPTION: When a time out occurs this function will be called..
** 
** PARAMETERS:
**				  	contents(IN) : SipEventContext.
** Return Value:
**				  SipBool	
*******************************************************************************/
extern void sip_indicateTimeOut( SipEventContext *context ) ;
#endif

/*******************************************************************************
** FUNCTION: sip_freeSipTimerBuffer
** DESCRIPTION: This function frees teh timer buffer structure
** of the timeout Context
** 
** PARAMETERS:
**      	      	b(IN)	:The SipMessage
** Return Value:
**				  void	
*******************************************************************************/



extern void sip_freeSipTimerBuffer(SipTimerBuffer *buf);

#endif


/* Ensure Names are not mangled by C++ compilers */
#ifdef __cplusplus
}
#endif 

