/*------------------------------------------------------------------------------
 *
 * File name        : icf_nm_defs.h
 *
 * Purpose          : This file contains the defines used by Network Manager(NM).
 *
 * Revision History :
 *
 * Date         Name            Ref#                Comments
 * --------     ------------    ----                ---------------
 * 01-Aug-2005	Irfan Khan		LLD					Initial
 * 06-Oct-2005	Ram Narayan 	LLD					Added FEW Defines related
 *                                                  to P-Access-Network-Info
 * 
 * Copyright (c) 2006, Aricent.
 *----------------------------------------------------------------------------*/



#ifndef __ICF_NM_DEFS_H__
#define __ICF_NM_DEFS_H__


/*
 * Determine if a C++ compiler is being used. If so, ensure that standard C is 
 * used to process the header information.
 */

#ifdef __cplusplus

/* Yes, C++ compiler is present. Use standard C */

extern "C"
{
#endif /* __cplusplus */



#define ICF_3GPP_GERAN       (0)
#define ICF_3GPP_UTRAN_FDD   (1)
#define ICF_3GPP_UTRAN_TDD   (2)
#define ICF_3GPP_CDMA2000    (3)

#define ICF_MNC_LEN_TWO      (2)
#define ICF_MNC_LEN_THREE    (3)

#ifdef ICF_NW_ACTIVATE
#define ICF_NM_MAX_PRIMARY_PDP_CONTEXTS 				1
#define ICF_NM_MAX_ACCESS_NW_TYPE					1
#define ICF_NM_MAX_SECONDARY_PDP_CONTEXTS			ICF_MAX_STREAM_PER_CALL
#endif

#ifdef ICF_QOS_SUPPORT
#define ICF_QOS_MIN_SEC_PDP_CTX_ID					1
#define ICF_QOS_MAX_SEC_PDP_CTX_ID					65535
#endif

/*ICF_RELEASE4_TBD*/
#define ICF_NM_MAX_CALLS 							5 
/*ICF_RELEASE4_TBD_END*/

#ifdef ICF_NW_ACTIVATE
#define ICF_NM_AUTOMATIC_PDP_CTXT_ID_GENERATION 		0 
#define ICF_NM_AUTOMATIC_SEC_PDP_CTXT_ID_GENERATION 	0 

#define ICF_NM_SEC_PDP_STATE_INACTIVE 				0
#define ICF_NM_SEC_PDP_STATE_PENDING_ACTIVATION		1
#define ICF_NM_SEC_PDP_STATE_ACTIVE     			2
#define ICF_NM_SEC_PDP_STATE_PENDING_DEACTIVATION   3

#define ICF_NM_INVALID_PRIMARY_PDP_CTXT_ID     			255
#define ICF_NM_DEFAULT_PRIMARY_PDP_CTXT_ID    			1
#define ICF_NM_PRIMARY_PDP_CTXT_DEACTIVATED_ID			255

#define ICF_NM_MAX_APNS				ICF_PORT_PLTFM_MAX_APNS			
#endif

#define ICF_NM_MAX_PUBLIC_USER_IDS	ICF_PORT_PLTFM_MAX_PUBLIC_USER_IDS	
#define ICF_NM_MAX_PCSCF_ADDRS		ICF_PORT_PLTFM_MAX_PCSCF_ADDRS	

#define	ICF_NM_AKA_SUCCESSFUL			ICF_PORT_PLTFM_AKA_SUCCESSFUL	
#define	ICF_NM_AKA_SEQRANGEERR		ICF_PORT_PLTFM_AKA_SEQRANGEERR	
#define ICF_NM_AKA_UNAUTHNWERR		ICF_PORT_PLTFM_AKA_UNAUTHNWERR	
#define ICF_NM_AKA_AKASYSTEMERR		ICF_PORT_PLTFM_AKA_AKASYSTEMERR	
#define ICF_NM_AKA_AKANULL			ICF_PORT_PLTFM_AKA_AKANULL	

#ifdef ICF_NW_ACTIVATE
#define ICF_NM_PRIMARY_PDP_CNTXT		ICF_PORT_PLTFM_PRIMARY_PDP_CNTXT	
#define ICF_NM_SECONDARY_PDP_CNTXT	ICF_PORT_PLTFM_SECONDARY_PDP_CNTXT	 

#define ICF_NM_PDP_TYPE_IPV4			ICF_PORT_PLTFM_PDP_TYPE_IPV4	
#define ICF_NM_PDP_TYPE_IPV6			ICF_PORT_PLTFM_PDP_TYPE_IPV6	
#define ICF_NM_PDP_TYPE_DEFAULT		ICF_PORT_PLTFM_PDP_TYPE_DEFAULT	

#define  ICF_NM_PDP_CREATE_NEW_TFT			ICF_PORT_PLTFM_PDP_CREATE_NEW_TFT  			
#define  ICF_NM_PDP_DELETE_EXISTING_TFT		ICF_PORT_PLTFM_PDP_DELETE_EXISTING_TFT			
#define  ICF_NM_PDP_ADD_PKT_FILTERS_TFT		ICF_PORT_PLTFM_PDP_ADD_PKT_FILTERS_TFT			
#define  ICF_NM_PDP_REPLACE_PKT_FILTERS_TFT 	ICF_PORT_PLTFM_PDP_REPLACE_PKT_FILTERS_TFT		
#define  ICF_NM_PDP_DELETE_PKT_FILTERS_TFT 	ICF_PORT_PLTFM_PDP_DELETE_PKT_FILTERS_TFT		
#define  ICF_NM_PDP_NO_TFT_OPERATION 			ICF_PORT_PLTFM_PDP_NO_TFT_OPERATION		

#define ICF_NM_MAX_TFT_PKT_FILTER_LIST		ICF_PORT_PLTFM_MAX_TFT_PKT_FILTER_LIST	    
#define ICF_NM_MAX_TFT_PARAMS_LIST			ICF_PORT_PLTFM_MAX_TFT_PARAMS_LIST	    

#define ICF_NM_MAX_TFT_PKT_FILTER_OCTET		ICF_PORT_PLTFM_MAX_AUTH_TOKEN_OCTET	    

#define ICF_NM_PDP_PARAM_IDENT_AUTH_TOKEN		 ICF_PORT_PLTFM_PDP_PARAM_IDENT_AUTH_TOKEN	    
#define ICF_NM_PDP_PARAM_IDENT_FLOW_ID 		 ICF_PORT_PLTFM_PDP_PARAM_IDENT_FLOW_ID	    
#define ICF_NM_MAX_TFT_FLOW_IDS				 ICF_PORT_PLTFM_MAX_TFT_FLOW_IDS	    

#define ICF_NM_QOS_CONVERSATIONAL_TRAFFIC_CLASS		ICF_PORT_PLTFM_QOS_CONVERSATIONAL_TRAFFIC_CLASS
#define ICF_NM_QOS_STREAMING_TRAFFIC_CLASS			ICF_PORT_PLTFM_QOS_STREAMING_TRAFFIC_CLASS
#define ICF_NM_QOS_INTERACTIVE_TRAFFIC_CLASS			ICF_PORT_PLTFM_QOS_INTERACTIVE_TRAFFIC_CLASS
#define ICF_NM_QOS_BACKGROUND_TRAFFIC_CLASS			ICF_PORT_PLTFM_QOS_BACKGROUND_TRAFFIC_CLASS
#define ICF_NM_MAX_PDP_VAR_PARAMS					ICF_PORT_PLTFM_MAX_PDP_VAR_PARAMS
#endif/*#ifdef ICF_NW_ACTIVATE*/


#define ICF_NM_DCOMP_OFF					ICF_PORT_PLTFM_DCOMP_OFF			
#define ICF_NM_DCOMP_ON					ICF_PORT_PLTFM_DCOMP_ON			
#define ICF_NM_DCOMP_V42BIS				ICF_PORT_PLTFM_DCOMP_V42BIS			
#define ICF_NM_DCOMP_V44BIS				ICF_PORT_PLTFM_DCOMP_V44BIS			
#define ICF_NM_DCOMP_DEFAULT				ICF_PORT_PLTFM_DCOMP_DEFAULT			

#define ICF_NM_HCOMP_OFF					ICF_PORT_PLTFM_HCOMP_OFF			
#define ICF_NM_HCOMP_ON					ICF_PORT_PLTFM_HCOMP_ON			
#define ICF_NM_HCOMP_RFC1144				ICF_PORT_PLTFM_HCOMP_RFC1144			
#define ICF_NM_HCOMP_RFC2507				ICF_PORT_PLTFM_HCOMP_RFC2507			
#define ICF_NM_HCOMP_RFC3095				ICF_PORT_PLTFM_HCOMP_RFC3095			
#define ICF_NM_HCOMP_DEFAULT				ICF_PORT_PLTFM_HCOMP_DEFAULT			

#define ICF_NM_PCSCF_ADDR				ICF_PORT_PLTFM_PCSCF_ADDR			
#define ICF_NM_DNS_ADDR					ICF_PORT_PLTFM_DNS_ADDR			
#define ICF_NM_IM_CN_SIG_FLAG			ICF_PORT_PLTFM_IM_CN_SIG_FLAG

/* icf_nm_network_event_t */
#ifdef ICF_NW_ACTIVATE

#define	ICF_NM_SIM_INSERTED				ICF_PORT_PLTFM_SIM_INSERTED
#define ICF_NM_SIM_REMOVED				ICF_PORT_PLTFM_SIM_REMOVED
#define ICF_NM_NW_FAILURE				ICF_PORT_PLTFM_NW_FAILURE
#define ICF_NM_NW_UP					ICF_PORT_PLTFM_NW_UP
#define ICF_NM_GPRS_FAILURE				ICF_PORT_PLTFM_GPRS_FAILURE
#define ICF_NM_GPRS_ON_HOLD				ICF_PORT_PLTFM_GPRS_ON_HOLD
#define ICF_NM_NWF_RECOVER				ICF_PORT_PLTFM_NW_RECOVER
#define ICF_NM_GPRS_RECOVED				ICF_PORT_PLTFM_GPRS_RECOVED
#define ICF_NM_NW_AC_INFO_CHANGE		ICF_PORT_PLTFM_NW_AC_INFO_CHANGE
#define ICF_NM_SYS_POW_RES				ICF_PORT_PLTFM_SYS_POW_RES
#define ICF_NM_SYS_MEM_RES				ICF_PORT_PLTFM_SYS_MEM_RES
#define ICF_NM_NW_CHNGE					ICF_PORT_PLTFM_NW_CHNGE


/* As per given by Priyanka */
#define ICF_NM_NW_NOT_AVAILABLE			ICF_PORT_PLTFM_NW_NOT_AVAILABLE
#define ICF_NM_NW_UNATTACHED			ICF_PORT_PLTFM_NW_UNATTACHED
#define ICF_NM_NW_ACTIVE				ICF_PORT_PLTFM_NW_ACTIVE
#define ICF_NM_NW_SUSPENDED				ICF_PORT_PLTFM_NW_SUSPENDED
#define ICF_NM_NW_REG_NOT_AVAILABLE		ICF_PORT_PLTFM_NW_REG_NOT_AVAILABLE
#define ICF_NM_NW_REG_UNKNOWN			ICF_PORT_PLTFM_NW_REG_UNKNOWN
#define ICF_NM_NW_REG_NO_SERVICE		ICF_PORT_PLTFM_NW_REG_NO_SERVICE
#define ICF_NM_NW_REG_EMERGENCY_ONLY	ICF_PORT_PLTFM_NW_REG_EMERGENCY_ONLY
#define ICF_NM_NW_REG_SEARCHING			ICF_PORT_PLTFM_NW_REG_SEARCHING
#define ICF_NM_NW_REG_BUSY				ICF_PORT_PLTFM_NW_REG_BUSY
#define ICF_NM_NW_REG_DENIED			ICF_PORT_PLTFM_NW_REG_DENIED

#endif

#define ICF_DUMMY_ID_FOR_NON_IMS		ICF_NULL

#ifdef __cplusplus
}

#endif /* __cplusplus */



#endif /* End of ifndef __ICF_NM_DEFS_H__ */

